### ISSUE TITLE
`-swb`: add a class which gets added/removed as the notification centre is toggled

### ISSUE THREAD

**Issue by neon64** [ErikReider/SwayNotificationCenter#101]
In my current waybar setup I have a few buttons which show visual toggle states , i.e.: they get a slightly different background colour etc... when activated.

I added a button to toggle swaync's notification center following this example: https://github.com/ErikReider/SwayNotificationCenter#waybar-example, but as an enhancement to that, what I thought would be really cool would be if `swaync-client -swb` would also emit new lines when the notification center is opened/closed, and it would toggle a particular class so that we could style the "toggle" state with Waybar's own css file.

e.g. something like:
```
{"text": "", "alt": "notification", "tooltip": "", "class": "notification"}
// after user opens notification center
{"text": "", "alt": "notification", "tooltip": "", "class": "notification notification-center-open"}
// after user closes notification center
{"text": "", "alt": "notification", "tooltip": "", "class": "notification"}
```

Awesome project by the way!

**Comment by ErikReider** [comment]
I'll look into this :)
