### ISSUE TITLE
Key binding to close notification outside of center

### ISSUE THREAD

**Issue by elshize** [ErikReider/SwayNotificationCenter#112]
I haven't found a way to close a notification with a key combination. I mean not inside the notification center, but rather the notification window that pops up. Essentially, I'd like to emulate clicking the X icon in the corner to dismiss it right away instead of waiting.

It seems like `swaync-client` can't do that, I only found a way to clear _all_ notifications, but I'm looking to dismiss them, and not clear altogether.

Is this possible to do currently in any way? If no, I think it would be a good idea for a new feature.

**Comment by ErikReider** [comment]
I'll look into this

**Comment by ErikReider** [comment]
@elshize does the branch fit your needs? :)

**Comment by elshize** [comment]
@ErikReider yep, just what I was looking for :) also love that there are options for both hide and close, depending on which action you want to take :rocket: 

Also, just compiled and tested, and works great :muscle:

**Comment by ErikReider** [comment]
Cool! Then I'll merge it :)
