### ISSUE TITLE
Long lines get truncated instead of overflowing into the next one

### ISSUE THREAD

**Issue by ptrcnull** [ErikReider/SwayNotificationCenter#115]
```
# notify-send aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

![image](https://user-images.githubusercontent.com/26630168/165426066-bda8cb6c-48c0-47e8-89e5-89dbe9e9776b.png)

It can be "fixed" by removing `ellipsize` on the GtkLabel#body element, but then it fails to calculate the notification height properly...

![image](https://user-images.githubusercontent.com/26630168/165426512-10d47ace-4304-465e-aa9e-2dd38c6ef626.png)

**Comment by ErikReider** [comment]
That's the hacky fix...

Related to #37

**Comment by ptrcnull** [comment]
Is that fixed properly then? If not, I think the issue should stay open :thinking:

**Comment by ErikReider** [comment]
I'm actually not sure if this is the first issue created for this bug
