### ISSUE TITLE
Only support compliant markup tags

### ISSUE THREAD

**Issue by ptrcnull** [ErikReider/SwayNotificationCenter#116]
```
$ swaync

(swaync:16054): Gtk-WARNING **: 04:27:35.762: Failed to set text '<thing> asdf' from markup due to error parsing markup: Error on line 1 char 29: Element “markup” was closed, but the currently open element is “thing”
Could for some reason not set markup. Text: &lt;thing&gt; asdf

(swaync:16054): Gtk-WARNING **: 04:27:35.815: Failed to set text '<thing> asdf' from markup due to error parsing markup: Error on line 1 char 29: Element “markup” was closed, but the currently open element is “thing”
Could for some reason not set markup. Text: &lt;thing&gt; asdf
```

To reproduce:
```
$ notify-send test '<thing> asdf'
```

This is usually an issue with IRC messages which use that format as the message body.

**Comment by ErikReider** [comment]
It only supports [Pango Markup](https://docs.gtk.org/Pango/pango_markup.html). "<thing>" isn't one of them. 

Could you post an IRC example? :)

**Comment by ErikReider** [comment]
> irc messages (sometimes) get sent as notifications with the equivalent of `notify-send "buffer/networkname" "<ircuser> message"`, so the message contents look like an open html tag
> 
> if that irc user is also named `small` and ends their message with </small>, then it would ensmallen the notification text :)

Well that's inconvenient...

**Comment by ptrcnull** [comment]
there's a similar thing happening with spotify songs that have `&` in them:
```
(swaync:20712): Gtk-WARNING **: 02:52:23.916: Failed to set text 'Futurecop! - The Unicorn & the Lost City of Alvograth' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
Could for some reason not set markup. Text: Futurecop! - The Unicorn &amp; the Lost City of Alvograth
```
i don't think swaync should be parsing all that as html really

**Comment by ErikReider** [comment]
@ptrcnull Do the notifications display correctly? That's an internal warning then trying to parse invalid markup. I'll close the issue for now

https://github.com/ErikReider/SwayNotificationCenter/blob/c54bf8ba16d5558082d5337cf24a87f9956c067b/src/notification/notification.vala#L203-L226

**Comment by ptrcnull** [comment]
They do, because it falls back to the escaped text; it's still invalid behaviour in my opinion, given that the spec only specifies a handful of valid markup tags and no support for HTML entities at all:

https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#markup

**Comment by ErikReider** [comment]
So you're talking about only parsing valid tags? So if I run this `notify-send "Summary" "<very_invalid_tag> normal text, <small>very tiny text</small>"`, only the "small" tag would be parsed?

**Comment by ptrcnull** [comment]
Yes, that (except that the `<small>` tag isn't technically supported per specification and shouldn't be used by any app), and also escaping the `&` sign before passing it to Pango - a _lot_ of notifications can have a standalone `&` character and currently it prints 2 warnings to the stderr on every such notification.

As a sidenote, it would be cool to be able to just disable markup entirely in the options and skip [exporting](https://github.com/ErikReider/SwayNotificationCenter/blob/c54bf8ba16d5558082d5337cf24a87f9956c067b/src/notiDaemon/notiDaemon.vala#L107) the `body-markup` capability; in the ideal situation, the protocol would have a field to determine whether the message should be parsed as markup, but sadly it doesn't...

**Comment by ErikReider** [comment]
@ptrcnull does the PR fix your issue?

**Comment by nekopsykose** [comment]
can confirm it fixes both the <something> and the & cases
