### ISSUE TITLE
PKGBUILD for aarch_64 devices

### ISSUE THREAD

**Issue by ErikReider** [ErikReider/SwayNotificationCenter#122]
Would require `gtk3-mobile` instead of `gtk3`

**Comment by ragreenburg** [comment]
I made the comment on the AUR post. I could also just make a PKGBUILD that is something along the lines or `swaync-mobile`?

**Comment by ErikReider** [comment]
I'd prefer `arm` instead of `mobile`. What do other arm AUR packages do?

**Comment by ragreenburg** [comment]
Just from a quick look, `-arm` seems a fair bit more popular. I just wasn't sure if `gtk3-mobile` is used on other ARM devices, as I'm using a [PinePhone](https://pine64.com/product/pinephone-pro-explorer-edition/), so I'm not sure if it is just mobile specific.

**Comment by ErikReider** [comment]
I can't seem to find the `gtk3-mobile` package anywhere. I've search through the official packages and AUR but nothing found? Which mirrors are you using?

**Comment by ragreenburg** [comment]
I think the repo is [https://p64.arikawa-hi.me](https://p64.arikawa-hi.me). So it might be specific for the PinePhone/PINE64.

**Comment by ErikReider** [comment]
Then there's nothing that I can do until Arch ships a arm64 native gtk3 package

**Comment by mpldr** [comment]
https://archlinuxarm.org/packages/armv7h/gtk3 It does (At least the only ARM Arch I know of does)

**Comment by ErikReider** [comment]
> https://archlinuxarm.org/packages/armv7h/gtk3 It does (At least the only ARM Arch I know of does)

Oh cool! I didn't know about that site! Then the script should in theory work but I have no way of testing it. I'll come back to this when GitHub supports running arm64 docker images for testing
