### ISSUE TITLE
Cannot change the position of control center and notification window.

### ISSUE THREAD

**Issue by so1ar** [ErikReider/SwayNotificationCenter#124]
I'm using Archlinux with sway and [swaync](https://aur.archlinux.org/packages/swaync) package from AUR.

I was able to change the position just fine by modifying `positionX` and `positionY` in the config file. But when I upgraded swaync from version 0.5 to version 0.6, these configurations are no longer taking effect. The position won't change no matter how I modify the config file.

**Comment by ErikReider** [comment]
I'll look into this

**Comment by ErikReider** [comment]
Should be fixed now. I'll update the releases :)

**Comment by so1ar** [comment]
> Should be fixed now. I'll update the releases :)

That's really quick, much appreciated :+1:
