### ISSUE TITLE
What CSS class to style "Notification" text

### ISSUE THREAD

**Issue by ldelossa** [ErikReider/SwayNotificationCenter#127]
Hey there, 

been using swaync for awhile now. It's been great and rock solid. I'm just having a small issue finding the class in CSS to style for this portion of the notification center UI.

![image](https://user-images.githubusercontent.com/5642902/169094100-97d7eb2d-4ccd-4876-b168-49b70a520e8d.png)

I want to change the text color of "Notifications" and "do not disturb".

**Comment by ErikReider** [comment]
It's `.top-action-title`. I'll add it to he default style :)

**Comment by ldelossa** [comment]
Thank you!!
