### ISSUE TITLE
[Feature Request] Close notification center after pushing 'Clear all' button

### ISSUE THREAD

**Issue by ajboni** [ErikReider/SwayNotificationCenter#128]
Maybe there is no point on having it open any more?

**Comment by ErikReider** [comment]
The config option `hide-on-clear` does this already

**Comment by ErikReider** [comment]
If you have any other suggestions, please open another issue. Really helps me know what's missing :)

**Comment by ajboni** [comment]
woops, sorry about that, and thanks for this aweosome project!!
