### ISSUE TITLE
[Feature Request] How to set image height/width?

### ISSUE THREAD

**Issue by TheMY3** [ErikReider/SwayNotificationCenter#131]
Try to set image height\width adding this params to `.image` and `.body-image`, but when I run `swaync-client -rs` I got `CSS reload success: false`, when I removed it - `CSS reload success: true`.

Is it possible to make images smaller?

**Comment by ErikReider** [comment]
Not at the time of writing... The size is being set through Vala. GTK css only supports some standard css attributes. This would be a good addition to the config file.

Maybe try setting min-height/width in the mean time?

**Comment by ErikReider** [comment]
https://github.com/ErikReider/SwayNotificationCenter/blob/725b80c615a17e34fcc33d4644fb3e8184bb19db/src/notification/notification.vala#L40

**Comment by TheMY3** [comment]
Ok, I am waiting for this attribute in config :) 

I try to do small notification block, already changed to smaller font, but icon too large, and notification block can't decrease because of it

**Comment by TheMY3** [comment]
Thank you, I use https://aur.archlinux.org/packages/swaync, I plan to go swaync-git for new updates :)

**Comment by ErikReider** [comment]
Probably when there's a few more features, a big new feature or a bug found

**Comment by ErikReider** [comment]
@TheMY3 the v0.6.2 is now released :)

**Comment by TheMY3** [comment]
@ErikReider thank you, downloading :)
