### ISSUE TITLE
Broken control center behavior on wayfire

### ISSUE THREAD

**Issue by Manky201** [ErikReider/SwayNotificationCenter#136]
https://user-images.githubusercontent.com/80580574/175807336-f4550a28-bb6d-441a-8078-bfd59e44909c.mp4

After the recent updates about `BlankWindow` control center controls are no longer clickable and intractable. Cannot reproduce on sway.

**Comment by ErikReider** [comment]
The provided video seems to be corrupted

**Comment by ErikReider** [comment]
But my initial guess would be that Wayfire handles their layers differently than sway but I'll need a look at the video to be sure

**Comment by Manky201** [comment]
https://user-images.githubusercontent.com/80580574/175807688-ec03420c-8e22-4e9d-8db9-b4b6af41e7d6.mp4

i can play the video here. recorded again just in case ....

**Comment by ErikReider** [comment]
This is what I see on Firefox:
![image](https://user-images.githubusercontent.com/35975961/175807830-9e6aed6c-2802-4b54-b0a3-969a0c1bf816.png)
The Github app displays a broken video and chromium freezes while displaying the initial thumbnail??? Strange

**Comment by Manky201** [comment]
https://user-images.githubusercontent.com/80580574/175807948-deb20dbb-fb3d-4187-b6a1-b02f2e5bc54b.mp4

strange indeed i recorded with wf-recorder earlier. This one is recorded with OBS

**Comment by ErikReider** [comment]
The video works if I download it and run it through Clapper. The latest works though. Strange...

**Comment by Manky201** [comment]
i have no idea, sorry for the issue

**Comment by ErikReider** [comment]
Nw! So my uneducated guess would be that Wayfire adds the newest layered windows above the older ones while Sway does the opposite. You can test this by running `sleep 5; notify-send "test" "test"` and locking the screen. Sway won't show the notification while I'm guessing that Wayfire does?

**Comment by Manky201** [comment]
Yes, notifications appear on swaylock

**Comment by ErikReider** [comment]
What I can do is to expose the click to close as a option in the settings but that is only a half baked solution to this issue

**Comment by Manky201** [comment]
or maybe allow the user to choose layer ? or is it possible for the BlankWindow and ControlCenter Window to be in same window ?

**Comment by ErikReider** [comment]
Hmmm. The issue with that would be if the user wants to blur the control center but not the translucent clickable background. I'll have to think about this one 🤔

**Comment by Manky201** [comment]
https://github.com/ErikReider/SwayNotificationCenter/blob/01a35a05c2f416fc2796476e2461233d7b59597a/src/controlCenter/controlCenter.vala#L149 replacing `GtkLayerShell.Layer.TOP` with `GtkLayerShell.Layer.OVERLAY` i can interact with the control-center and click to close works as well.

**Comment by Manky201** [comment]
After using OVERLAY Layer for control center

Wayfire:

https://user-images.githubusercontent.com/80580574/175821780-751e8e98-61f4-4f6b-b4d9-83aa5b109029.mp4


Sway:

https://user-images.githubusercontent.com/80580574/175821792-6179929c-287d-4ee8-989c-e474dffab844.mp4

**Comment by ErikReider** [comment]
The only reason why the control center isn't using that layer by default is due to it appearing above the lockscreen on sway. Seems like that won't be the case on Wayfire and hyprland. The layer shell protocol is unstable atm so adding it as a config option isn't ideal if they change the spec in the future.

What would be ideal would be if the lockscreen had its own layer above everything else...

**Comment by ErikReider** [comment]
I'm cooking up a solution for this. Should be a PR that you can test soon :)

**Comment by ErikReider** [comment]
Does #139 fix the issue?

**Comment by Manky201** [comment]
Yes, everything is working fine now.

**Comment by ArchieSW** [comment]
Same issue on hyprland now

**Comment by ErikReider** [comment]
> Same issue on hyprland now

Are you using the latest changes? (Not the release version)

**Comment by ArchieSW** [comment]
> > Same issue on hyprland now
> 
> Are you using the latest changes? (Not the release version)

I am using the version from AUR 0.6.3-1

**Comment by ErikReider** [comment]
> I am using the version from AUR 0.6.3-1

Use the -git version

**Comment by ArchieSW** [comment]
Sorry for late answer. I checked with git version in aur, that contains master version of swaync, and all works correctly.
