### ISSUE TITLE
Settings schema 'org.erikreider.swaync' is not installed

### ISSUE THREAD

**Issue by freijon** [ErikReider/SwayNotificationCenter#137]
I'm using SwayNotificationCenter on Gentoo and with version 0.6.3 I get the following error when lauching `swaync`:

> ❯ swaync
(swaync:10182): GLib-GIO-ERROR **: 20:22:23.921: Settings schema 'org.erikreider.swaync' is not installed
[1]    10182 trace trap  swaync

Here are the files installed by the Gentoo package:

```
/etc
/etc/xdg
/etc/xdg/swaync
/etc/xdg/swaync/config.json
/etc/xdg/swaync/configSchema.json
/etc/xdg/swaync/style.css
/usr
/usr/bin
/usr/bin/swaync
/usr/bin/swaync-client
/usr/lib64
/usr/lib64/systemd
/usr/lib64/systemd/user
/usr/lib64/systemd/user/swaync.service
/usr/share
/usr/share/bash-completion
/usr/share/bash-completion/completions
/usr/share/bash-completion/completions/swaync
/usr/share/bash-completion/completions/swaync-client
/usr/share/dbus-1
/usr/share/dbus-1/services
/usr/share/dbus-1/services/org.erikreider.swaync.service
/usr/share/doc
/usr/share/doc/swaync-0.6.3
/usr/share/doc/swaync-0.6.3/README.md.bz2
/usr/share/fish
/usr/share/fish/vendor_completions.d
/usr/share/fish/vendor_completions.d/swaync-client.fish
/usr/share/fish/vendor_completions.d/swaync.fish
/usr/share/glib-2.0
/usr/share/glib-2.0/schemas
/usr/share/glib-2.0/schemas/org.erikreider.swaync.gschema.xml
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/swaync-client.1.bz2
/usr/share/man/man1/swaync.1.bz2
/usr/share/man/man5
/usr/share/man/man5/swaync.5.bz2
/usr/share/zsh
/usr/share/zsh/site-functions
/usr/share/zsh/site-functions/_swaync
/usr/share/zsh/site-functions/_swaync-client
```
What stands out is the `/usr/share/glib-2.0/schemas/org.erikreider.swaync.gschema.xml` file which is installed, but I don't know if the path is correct. Apparently not, otherwise it would read/detect it.

What am I missing here?

**Comment by ErikReider** [comment]
Mine is also installed there. Try running `glib-compile-schemas /usr/share/glib-2.0/schemas`. `postinstall.py` should compile it automatically though...

**Comment by freijon** [comment]
> Edit: Try this branch instead: https://github.com/ErikReider/SwayNotificationCenter/tree/postinstall-fix

Just gave it a try - during compilation I saw this line:
> Running custom install script '/var/tmp/portage/gui-apps/swaync-0.6.3/work/SwayNotificationCenter-0.6.3/build-aux/meson/postinstall.py'

however, after trying to launch `swaync` I still get the same error message

**Comment by ErikReider** [comment]
What if you manually run `glib-compile-schemas /usr/share/glib-2.0/schemas`?

**Comment by freijon** [comment]
After this command it works

**Comment by ErikReider** [comment]
Strange... It does the exact same thing unless the path in the script is incorrect

**Comment by ErikReider** [comment]
What's the output of the script if you add `print(['glib-compile-schemas', path.join(datadir, 'glib-2.0', 'schemas')])` before the call method?

**Comment by freijon** [comment]
Unfortunately: nothing... I also don't see `Compiling GSettings schemas...`
If I add a print before `if not destdir:` I also don't see anything in the output, which makes me believe the script is not actually executed.

**Comment by freijon** [comment]
I played around a bit... Seems the "print" is suppressed somehow... But if I write to a debug file on /tmp I can see the messages.
Turns out everything under `if not destdir:` is not executed because `destdir = /var/tmp/portage/gui-apps/swaync-0.6.3/image`

**Comment by ErikReider** [comment]
Seems like that it's standard to skip compiling if destdir is exported. Why would you need that? Wouldn't the regular directory be better?

**Comment by freijon** [comment]
This is apparently done by portage (package manager of Gentoo). everything is compiled and installed in a sandbox and finally the contents in the 'image' folder are copied to the filesystem

**Comment by ErikReider** [comment]
Hmmm... `makepkg` does the same thing but that seems to work as expected

**Comment by ErikReider** [comment]
Seems like there's a pacman hook for compiling the gsettings. I'll double check this

**Comment by freijon** [comment]
Maybe a stupid question, but how can I undo `glib-compile-schemas` ? I'd like to revert it and to test how I could fix it.

**Comment by ErikReider** [comment]
I'm not sure if this is the preferred method but here:
```sh
sudo rm /usr/share/glib-2.0/schemas/org.erikreider.swaync.gschema.xml
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```
