### ISSUE TITLE
[Feature request] Add a state between 'muted' and 'ignored' for 'notification-visibility'

### ISSUE THREAD

**Issue by rgouicem** [ErikReider/SwayNotificationCenter#146]
It would be nice to have a state between `muted` and `ignored` that:
- doesn't show the notification (like `muted` and `ignored`)
- doesn't change the state for waybar when a notification arrives (like `ignored`)
- still shows the notification in the notification center (like `muted`)

My use case here is media players that trigger a notification every time they switch track (e.g. Spotify). For this type of applications, I don't want notifications to pop up every time, and I don't want to see a change in my waybar module either. However, I still want to see which track is playing when I open the notification center.

I can try looking into this when I have some time. But from what I have seen, it would require to distinguish between different types of notifications (this new state and others) when generating the json for waybar. And currently, it's just taking the size of the list of notifications.

**Comment by ErikReider** [comment]
I'm back from my vacation. I'll look into this :)

**Comment by ErikReider** [comment]
I can't really think of a good use case for this except for music player notifications which would be worse than a player widget in Waybar or even in the Control Center. I'll close this for now...

I'd gladly accept a media player widget :)

**Comment by ErikReider** [comment]
#150 should make it a lot easier to create widgets
