### ISSUE TITLE
Ability to use GTK Inspector

### ISSUE THREAD

**Issue by thomascft** [ErikReider/SwayNotificationCenter#153]
Is there a way to use `GTK_DEBUG=interctive swaync` effectively? When I try to select items in the inspector it closes the notification shade. Could you add a flag to the client?

**Comment by ErikReider** [comment]
This is due to the "click to close" functionality of the ControlCenter. What I can do is to disable click to close when the `GTK_DEBUG=interctive` variable is passed to swaync

**Comment by ErikReider** [comment]
I might have misspoken... A large GTK window covers the whole screen to grab the clicks and I'm not sure if I'm able to pass those click events through to windows below...

For now, you can always navigate the structure in the GUI without the "click to inspect" feature

**Comment by ErikReider** [comment]
So the builtin Gdk.Window.pass_through option which would enable me to fix this isn't working. Probably only works on Gnome... Try what I mentioned above :)

**Comment by paul-ri** [comment]
After clicking on "select items" it closes the notification panel for me too. Yet, on Sway, simply re-opening it with the keyboard shortcut associated to it allows to select the items
