### ISSUE TITLE
Customisable Notification timeout: Allow 0 to disable for low and normal notifications

### ISSUE THREAD

**Issue by mox-mox** [ErikReider/SwayNotificationCenter#154]
Hi,

thank you for writing/maintaining swaync!
I would like to disable the timeout for `normal` notifications just like or `critical` ones. But it seems this is not possible.  Could you please enable this feature for the `normal` and `low` urgency notification timeout config options as well?

Best regards,
mox

**Comment by ErikReider** [comment]
Fixed :)

**Comment by mox-mox** [comment]
Thank You!
