### ISSUE TITLE
GTKLAYERSHELL IS NOT SUPPORTED

### ISSUE THREAD

**Issue by cvasilak** [ErikReider/SwayNotificationCenter#155]
Hello there,

thank you for your work on this. Attempting to run `swaync` I get the following error message:

`
** (swaync:26161): WARNING **: 14:25:38.568: It appears your Wayland compositor does not support the Layer Shell protocol
GTKLAYERSHELL IS NOT SUPPORTED!
Swaync only works on Wayland!
If running waylans session, try running:
    GDK_BACKEND=wayland swaync
`

The same happens when using the prefix GDK_BACKEND as suggested in the message.

* I am on Fedora 36 using Wayland

**Comment by ErikReider** [comment]
Which WM are you using?

**Comment by Ridhubharan** [comment]
Same issue. Also running Fedora 36(gnome) using Wayland.

**Comment by ErikReider** [comment]
Swaync doesn't support Gnome or rather Gnome doesn't support the layershell standard

**Comment by Ridhubharan** [comment]
That's funny because this software was recommended by Fedora in their newsletter!

**Comment by ErikReider** [comment]
@Ridhubharan Could you send me the link? Would be fun to read :)

**Comment by cvasilak** [comment]
@Ridhubharan indeed, found out about the project cause it was mentioned in the Fedora newsletter 🙂

[https://fedoramagazine.org/4-cool-new-projects-to-try-in-copr-for-august-2022/](https://fedoramagazine.org/4-cool-new-projects-to-try-in-copr-for-august-2022/)

**Comment by ErikReider** [comment]
I'll update the README with info about which WMs are supported. The current layershell protocol is unstable but a new one is in the works [Draft: ext-layer-shell: new protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28)

So if Gnome would support that protocol, this would theoretically work?

**Comment by Ridhubharan** [comment]
Ok. If it does work in the future, ping me!

**Comment by ErikReider** [comment]
Will do! :)
