### ISSUE TITLE
The gesture bug with the notification.

### ISSUE THREAD

**Issue by asas1asas200** [ErikReider/SwayNotificationCenter#159]
The notification can be swiped out by mouse dragging or touchpad two-finger swiping.

But the notification moves right when I swipe left with natural scrolling disabled.
If the natural scrolling is enabled, the notification will swipe with the finger scrolling direction.
The correct behavior should be the opposite direction.

I have tried adding `this.carousel.get_swipe_tracker().set_reversed(true);` in `notification.vala`, but it will cause mouse dragging with wrong direction.

**Comment by ErikReider** [comment]
That's how it's supposed to be. Think of it like physically touching and swiping the scrolled object away like a webpage or a notification (with natural scrolling enabled).

Or is this about swiping the same direction while natural scrolling is enabled and disabled?

**Comment by asas1asas200** [comment]
Or can it add a config against the touchpad direction?
I preferred the notification swiping and the touchpad scrolling in the same direction with natural scrolling disabled, just like macOS does.

**Comment by ErikReider** [comment]
I don't have a Mac so I can't test how their gestures work but elementary OS has a similar gesture. Do they have the same "issue"?

**Comment by asas1asas200** [comment]
Just like what I said above.

If I want to remove a notification appears on right top, and the natural scrolling is disabled, I should swipe right on that.

**Comment by ErikReider** [comment]
I just checked and Elementary OS and Mac OS notification gestures behave the same way as SwayNotificationCenter so I'll keep this closed.

You may be able to change a setting in gsettings but I'm not sure

**Comment by asas1asas200** [comment]
Do you mean this?
![image](https://blog.elementary.io/images/multitouch-gestures-in-elementary-os-6/notification-center.gif)

**Comment by ErikReider** [comment]
This is what I mean:

https://user-images.githubusercontent.com/35975961/187035781-1ee567a7-09d1-441e-8ffc-5a77423574ab.mp4

This is with natural scrolling enabled. See the notification following my hand gesture. Is this not the case on your setup with swaync?

**Comment by asas1asas200** [comment]
My case is the same as this.
But if I disable natural scrolling, this will go reverse.
And I want it works the same as natural scrolling enabled.
Whether it can add a config to change its behavior?

This direction is weird:

https://user-images.githubusercontent.com/11487756/187038071-300bc911-538c-48f8-bd2d-b4e706cfb0f7.mp4

**Comment by ErikReider** [comment]
Ooooooh. Now I get what you're referring to! I don't think that I can do anything to fix this due to it not being my widget that controls it. Maybe contact the libhandy devs by creating an issue on their GitLab?

**Comment by mike-lloyd03** [comment]
I know it's been a while, but I'm looking for the same functionality. Moving my fingers from left to right should move the notification from left to right and dismiss it. But it's the opposite (as shown in the video above).

I'm on hyprland and I'm not even aware of a way to set "natural scrolling" on or off.

Has there been any development on this or has anyone figured out a way to reverse the gesture direction?

**Comment by ErikReider** [comment]
> I know it's been a while, but I'm looking for the same functionality. Moving my fingers from left to right should move the notification from left to right and dismiss it. But it's the opposite (as shown in the video above).
> 
> I'm on hyprland and I'm not even aware of a way to set "natural scrolling" on or off.
> 
> Has there been any development on this or has anyone figured out a way to reverse the gesture direction?

Changing the libinput scrolling direction should change the direction
