### ISSUE TITLE
Apostrophes display as &apos;

### ISSUE THREAD

**Issue by giraudan** [ErikReider/SwayNotificationCenter#16]
It looks like certain characters need to be escaped (HTML entities?)

![image](https://user-images.githubusercontent.com/45098592/133580140-6d8fa03e-a073-4379-986f-29504b85d15c.png)

**Comment by ErikReider** [comment]
Hmmmm. Thats due to it using markdown instead of normal text

**Comment by giraudan** [comment]
Ah, indeed! If I just execute

```
notify-send "hello'world"
```

I don't reproduce the issue.

So it comes from the way this application sends the message. It's [`signal-desktop`](https://signal.org).

I tried it again with [`mako`](https://mako-project.org) instead, it seems to work fine:

![image](https://user-images.githubusercontent.com/45098592/133582595-3160235a-add9-48e6-b4fc-b4701e2f2cc3.png)

(In case it's not clear, my friend sent me a message with only 3 apostrophes).

**Comment by ErikReider** [comment]
So the title doesn't use markup while the body/content uses markup. I'll see if there's a way of parsing it into readable text

**Comment by ErikReider** [comment]
So discord doesn't send any markup. `notify-send.sh` sends markup.

`notify-send.sh "hello'world" "&&"`

**Comment by ErikReider** [comment]
```vala
try {
    var entity_regex = new Regex ("&(?!amp;|quot;|apos;|lt;|gt;)");
    text = entity_regex.replace (text, text.length, 0, "&amp;");
} catch (Error e) {
    stderr.printf ("Invalid regex: %s", e.message);
}
this.body.set_markup (text);
```
Seems to fix this. I'll test it some more

**Comment by ErikReider** [comment]
de7fa74f056bbe54bec013b6b5f4c1c0f6434a13 Should fix this. Let me know if it doesn't work 😄
