### ISSUE TITLE
Error when running `swaync`: `COULD NOT FIND CSS FILE! REINSTALL THE PACKAGE!`

### ISSUE THREAD

**Issue by perlinm** [ErikReider/SwayNotificationCenter#167]
If I install `swaync` and try to run it, I simply get the error message `COULD NOT FIND CSS FILE! REINSTALL THE PACKAGE!` and an exit code of 1.  I am running Ubuntu 22.04, and this occurs both if I try to build `swaync` from source and if I try to install it through `nix`.

I'm not sure what other info might help here, but I am willing to answer any questions.

**Comment by ErikReider** [comment]
Run `meson install -C your_build_dir`

**Comment by perlinm** [comment]
I did... Specifically, I ran
```
git clone https://github.com/ErikReider/SwayNotificationCenter.git
cd SwayNotificationCenter
meson build
ninja -C build
meson install -C build
swaync
```
[Here](https://github.com/ErikReider/SwayNotificationCenter/files/9648344/log.txt) is a log that I copy/pasted from my console.

**Comment by ErikReider** [comment]
Oh, my bad... Seems like it's installing those files into `/usr/local` when not finding the `MESON_INSTALL_PREFIX` env variable

**Comment by ErikReider** [comment]
Does #168 fix your issue?

**Comment by perlinm** [comment]
It does, thank you! :slightly_smiling_face: 

[Here's](https://github.com/ErikReider/SwayNotificationCenter/files/9658655/log.txt) a log for posteriority.
