### ISSUE TITLE
List of notifications can't be scrolled without clicking

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [ErikReider/SwayNotificationCenter#172]
I just noticed that the list of notifications can't be scrolled without clicking on it first. I would expect the notification list to have focus when the mouse is over it.

# Steps to reproduce

1. Populate the panel with more notifications than can fit on the screen.
2. Open the panel, hover over the list of notifications, try to scroll.

# Expected behaviour

List scrolls down allowing you see older notifications.

# Actual behaviour

Nothing happens.

**Comment by ErikReider** [comment]
Thanks for reporting. I won't be able to test/fix this for a few weeks (info in README) but I'll get to it at some point :)

**Comment by FilippoBonazziSUSE** [comment]
Thanks, enjoy your holiday and get well soon

**Comment by ErikReider** [comment]
Hmm. Can't really seem to reproduce this. Are you able to reproduce it?

**Comment by ErikReider** [comment]
I've found a way of reproducing this issue:

1. Run swaync
2. Open ControlCenter
3. Click the outside of the ControlCenter to close
4. Reopen the ControlCenter

**Comment by FilippoBonazziSUSE** [comment]
Sorry I didn't get back to you. Your reproducer sounds sensible, I can't swear that's what I had done when I experienced the issue but it might well be. Will test the new release once it's out and will let you know if the issue persists, thanks.
