### ISSUE TITLE
Limit max visible notification

### ISSUE THREAD

**Issue by etrnal70** [ErikReider/SwayNotificationCenter#178]
Basically the title. Invisible notification can be replaced with a smaller notification showing there are X more new notification

**Comment by ErikReider** [comment]
Are you referring to something like #61?

**Comment by etrnal70** [comment]
No, i'm referring to the floating notification, not the notification center.

**Comment by ErikReider** [comment]
Oh. Could you elaborate some more? Maybe provide an example screenshot?

**Comment by ErikReider** [comment]
Hmm... That would be pretty difficult to add due to the scrolling and the variable height of each notification. 

I'd prefer a look that elementary OS uses where the other non visible notifications are behind the visible notifications and scrolls into view when scrolled (very difficult to explain)

**Comment by etrnal70** [comment]
> I'd prefer a look that elementary OS uses where the other non visible notifications are behind the visible notifications and scrolls into view when scrolled (very difficult to explain).

I get this. I think it's an acceptable solution too since i'm currently bothered by the number of visible notification. So can i assume such thing is planned ?

**Comment by ErikReider** [comment]
Yeah but it'll take time
