### ISSUE TITLE
Customisable Notification timeout 

### ISSUE THREAD

**Issue by roycefanproxy** [ErikReider/SwayNotificationCenter#18]
Hi,

Thanks for your awesome tools, I really like the design and ease of use of this tool. However, I would like to customise timeout length of a popping notification, is there a way to do so in config file?

**Comment by ErikReider** [comment]
At the moment the time is a set value which is also dependent on the notification urgency. How long of a delay would you prefer?

**Comment by mindrunner** [comment]
> How long of a delay would you prefer?

Since everyone has another preference, this should be part of the configuration file.

**Comment by WTechNinja** [comment]
I would like to mention, I've noticed that you can't have quotation marks around the timeout values, e.g
`"timeout": "3",`  won't work, swaync will use the default values instead, but
`"timeout": 3,`  works as intended.
Might be worth fixing or documenting.

**Comment by ErikReider** [comment]
@WTechNinja Yeah. It only parses the value if it's an integer

**Comment by ErikReider** [comment]
@WTechNinja Added extra clarification c3950c05680aa7c0553b7bc2056b39c72c3cf062
