### ISSUE TITLE
Allow separate positioning for control center and notification pop ups

### ISSUE THREAD

**Issue by zoro11031** [ErikReider/SwayNotificationCenter#180]
As far as I can tell from the man pages and documentation, if you position the control center in the center of your top bar, the notification pop ups will appear there too. I'd like the ability to keep the pop ups in the top right, but have the control center appear from the center when activated. Thank you!

**Comment by ErikReider** [comment]
Hmm. It would be difficult to maintain compatibility with older configs. I'm not really sure about what would be best to do in this situation...

**Comment by zoro11031** [comment]
Maybe it would be a good idea to implement the current behavior as default, and the separate positioning as optional that only activates when you add the config option to change the pop up position?

That way current configs would be unaffected I think

**Comment by ErikReider** [comment]
I think I've got an idea that might work...

Add two new position keys (something like `control-center-position-x`) for the control center and include a default enum constant that implies that the CC should follow the regular `position` keys
