### ISSUE TITLE
[FR] Add debian/ubuntu instructions

### ISSUE THREAD

**Issue by werdahias** [ErikReider/SwayNotificationCenter#188]
fyi, sway nc got accepted into debian. it will be part of the bookworm release (pretty sure) and ubuntu lunar (likely). Please add this in the README. Or you could add a repology tag ;)

**Comment by ErikReider** [comment]
Oh wow! That was quick! Thanks for the help!

I'll add it to the README right away!

**Comment by ErikReider** [comment]
Seems like it'll be in [Lunar](https://packages.ubuntu.com/lunar/sway-notification-center) and [Sid](https://packages.debian.org/source/sid/sway-notification-center)

**Comment by werdahias** [comment]
np :) bookworm freeze is in january so it should be part of the next debian release.

**Comment by ErikReider** [comment]
Fixed by: c2f675c
