### ISSUE TITLE
[Feature] Show notification content with swaync-client

### ISSUE THREAD

**Issue by aereaux** [ErikReider/SwayNotificationCenter#189]
**Please read through the README and the Man pages before submitting**
**Please also make sure that there isn't any prior issue describing this feature**

**Is your feature request related to a problem? Please describe.**
Right now it is impossible to get notification content for scripting or viewing outside of swaync.

**Describe the solution you'd like**
Adding a new option to swaync-client to get notifications as json, as plain text lines, or in a similar format.

**Describe alternatives you've considered**
Not sure what other options would be better, but also having the ability to do notification actions from swaync-client could be useful.

**Additional context**
Several other notification daemons (mako, fnott) offer this sort of feature, but they also don't have the notification center aspect of swaync

**Comment by ErikReider** [comment]
Have you considered using the built-in scripting support in the config?

**Comment by aereaux** [comment]
Thanks for the suggestion.  It doesn't look you can get notification content in the trigger script can you?  My primary use for this at the moment would be checking notifications when I'm away from my desktop.  That may be more of a niche concern however.

**Comment by ErikReider** [comment]
Check the script environment variables. If I remember correctly, there should be some exported variables with notification information

**Comment by aereaux** [comment]
Looks like you're right: https://github.com/ErikReider/SwayNotificationCenter/blob/12ec6012b4047c1aac2bed5edf84fa7e713f4472/src/configModel/configModel.vala#L217 .  Might work for my use case, I'll try it out

**Comment by ErikReider** [comment]
I'll close this then :)
