### ISSUE TITLE
Question: Customize buttons in mpris

### ISSUE THREAD

**Issue by laxyy69** [ErikReider/SwayNotificationCenter#195]
Is there a way to customize the buttons next to the media player in CSS? (It looks rather odd with my theme)
I looked, don't see a way to customize it (or maybe I am just blind?). It would be nice if you can do it. 
![screenshot_2023-01-03-141905](https://user-images.githubusercontent.com/74270998/210357141-d5154d4c-c7f7-48d2-92bb-449d3f236f97.png)

(I discovered SwayNC yesterday, I like it! :+1: )

**Comment by ErikReider** [comment]
It doesn't have its own CSS class but you can always do this instead:

```CSS
/* Insensitive button */
.widget-mpris > box > button:disabled {
}

/* Sensitive button */
.widget-mpris > box > button {
}
```
