### ISSUE TITLE
[Bug] Notification keep showing even after dnd (do not disturb) is enabled

### ISSUE THREAD

**Issue by mildred** [ErikReider/SwayNotificationCenter#198]
**Describe the bug**

After activating the Do Not Disturb mode, notification keep showing

**To Reproduce**

1. Install and enable swaync
2. ~Install the Telegram desktop client via flatpak/flathub org.telegram.desktop~
3. Enable do not disturb
4. ~Telegram notification keep showing~
5. Execute : `notify-send -u critical Foo`
6. Notification is showing despite DND mode

**Expected behavior**
Notification should not show up

**Please provide logs if you're experiencing notification errors / bugs**
Nothing, I don't know how to get the details about a notification with swaync-client or is that possible. I believe the telegram notification have a critical urgency because the notification do not auto hide with default config (well, that's ~another issue and~ the reason why I enabled the DND mode in the first place).

**Screenshots**

**Desktop (please complete the following information):**
 - Fedora 37
 - Version 0.7.3

**Additional context**
~The notification do not hide either despite a `"timeout-critical": 5,` in the settings~

**Comment by mildred** [comment]
This is apparently by design, urgent notifications are displayed even if there is DND set:

https://github.com/ErikReider/SwayNotificationCenter/blob/8a1ffcfd6f0eab565636103e3d9631ccec76d312/src/notiDaemon/notiDaemon.vala#L176-L182

And for some reason I could not always load my configuration file, probably because when dbus-activated, the path to my configuration file was not taken. The correct configuration file path is `~/.config/swaync/config.json` (with the .json extension) and then it will always be picked up.

**Comment by ErikReider** [comment]
Yeah. It's in the spec that urgent notifications should always be displayed to the user.

What config location were you using?

**Comment by mildred** [comment]
I was using `~/.config/swaync/config` instead and of course when swaync was executed by dBus it would not pick it up.

The problem wit hthis spec is that the application might not correctly set the urgency of the different notifications, it should be overridable by the user.
