### ISSUE TITLE
[Feature Request] - Add ability to configure Keyboardmode to prevent inhibition of keyboard during show of notification center

### ISSUE THREAD

**Issue by phwelo** [ErikReider/SwayNotificationCenter#20]
https://github.com/ErikReider/SwayNotificationCenter/blob/978f20de5f391ecc845844956b35be6f7f9b0969/src/controlCenter/controlCenter.vala#L98

Would like the ability to turn on and off this control, maybe in `config.json`

Tested with this line to verify:
```
GtkLayerShell.set_keyboard_mode (this, GtkLayerShell.KeyboardMode.NONE);
```

**Comment by ErikReider** [comment]
A keyboard shortcuts bool in the config would be fitting
