### ISSUE TITLE
systemd service: add more generic WantedBy

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [ErikReider/SwayNotificationCenter#205]
I have recently noticed that swanc ships its own systemd user service, so I decided to delete my [custom service](https://github.com/FilippoBonazziSUSE/dotfiles/commit/13db9a3d5a454c920555cabb56191510a2b488f3) and use the upstream provided one.

I enabled the service, but it doesn't autostart anyway. I think this is because the service has `WantedBy=graphical-session.target`, which is not reached on my system (I'm running sway and swaync on openSUSE Tumbleweed with the [openSUSEway](https://github.com/openSUSE/openSUSEway) configuration, using `greetd` and the custom `sway-run.sh` script).

Would it be possible to add a `WantedBy` on a more generic target? I was using `default.target` in my custom service and that worked. I'm not sure what the best target would be, but I'm thinking one of `default.target`, `graphical.target`, `multi-user.target`.

**Comment by berbiche** [comment]
Hi,

The recommended setup when using any wlroots-based compositor is to setup a systemd target that binds to `graphical-session.target`.
See the ArchWiki <https://wiki.archlinux.org/title/sway#Manage_Sway-specific_daemons_with_systemd>

> I was using `default.target` in my custom service and that worked

Generally you don't want to start Wayland/X11 services when sshing into a computer which is why the `default.target` is not used.

> I'm thinking one of `default.target`, `graphical.target`, `multi-user.target`.

The last two targets are unavailable in the user systemd session. They are only exposed in the system session.

Hope this helps 🙂

**Comment by FilippoBonazziSUSE** [comment]
Hi, thanks for the info. I agree `default.target` is not great. Still I'm at a loss on how to set this up.

I have a `sway-session.target` in the system systemd session. That cannot be started, as it requires `graphical-session.target` which is only present in the user systemd session. It's all a bit confusing and I'm not sure how to relate this to the information on the Arch wiki page.

**Comment by berbiche** [comment]
Hi,

Per the wiki, you need to setup the `sway-session` in the systemd user service.

**Comment by FilippoBonazziSUSE** [comment]
Thanks for the support, let me investigate. Hopefully it's just that and it's an easy fix :smile:

**Comment by FilippoBonazziSUSE** [comment]
Yep I'm opening an issue for openSUSEway as we speak

**Comment by FilippoBonazziSUSE** [comment]
Thanks for the support.

I am going to  close this issue since this seems to be a simple packaging/setup error in openSUSEway.
