### ISSUE TITLE
[Feature Request] Ability to close notification center upon mouseclick anywhere outside of notification center

### ISSUE THREAD

**Issue by phwelo** [ErikReider/SwayNotificationCenter#21]
Not sure if this is possible or not, but would love a setting to allow hiding of notification center upon either mouseclick outside of notification center or loss of focus from notification center.

**Comment by Hippo0o** [comment]
there could be a keybind in sway that triggers the close-panel.
that gets bound when swaync is opened and unbound when its is closed.
e.g.
`swaymsg -- bindsym --whole-window button1 exec swaync-client -cp`
and `swaymsg -- unbindsym --whole-window button1`

**Comment by ajboni** [comment]
This would be really useful for me. What about a transparent backdrop covering all the screen to capture clicks on?

**Comment by Ashe** [comment]
Another :+1: from me. Maybe it's just habit, but sometimes I forget the notification center is open and my computer becomes unresponsive (I have a very wide monitor and the center is nice and out of the way).

**Comment by ErikReider** [comment]
I would appreciate some help with testing :). Works on my end but I'm unsure if it'll work for other people with other setups

**Comment by Hippo0o** [comment]
works great for me with multiple monitors. I could style .blank-window transparent no problem. :+1:

**Comment by tukusejssirs** [comment]
I think I know where the culprit was: during my tests, I edited `src/styles.css` in the repo, which is (most probably) overriden by `~/.config/swaync/styles.css`.

When I set `.blank-window {background: transparent;}`, it works as expected. :man_facepalming:

**Comment by ErikReider** [comment]
@tukusejssirs not defining CSS classes are now fixed in 2fc2d86. It loads the packaged CSS file as a base and applies the user CSS file on top

**Comment by ajboni** [comment]
A little late, but working great with 3 monitors, the backdrop span all three monitors independent on where the NC is open.
This do NOT include the bar (using waybar) but its not an issue IMO.
This is such a great feature! thanks!!!

**Comment by tukusejssirs** [comment]
> This do NOT include the bar (using waybar) but its not an issue IMO.

What do you mean by this? In my case, when I click on my Waybar on any my three monitors, NC is closed.

If you look at the screenshot of [this comment](https://github.com/ErikReider/SwayNotificationCenter/issues/21#issuecomment-1157441837), the grey area covers everything but NC, and this grey area is kind of a large button to close NC overlay.

Unless I misunderstood your comment … :thinking:

**Comment by ErikReider** [comment]
@tukusejssirs your bar is probably using a lower layer than the control center

**Comment by tukusejssirs** [comment]
> @tukusejssirs your bar is probably using a lower layer than the control center

Is there a way how can I check if my bar is using a lower layer?

**Comment by ajboni** [comment]
> Unless I misunderstood your comment … thinking

No, you got that right, check this: (I've cxhange the css to blue to test)

![image](https://user-images.githubusercontent.com/12578313/174502778-e2a5454f-4ac2-4fab-84cb-e0a70b1c85d6.png)

Maybe try inverting the exec calls in wyour sway config?

**Comment by tukusejssirs** [comment]
> Maybe try inverting the exec calls in wyour sway config?

@ajboni, you mean that the layering depends on the order of the commands in Sway config (lower row → lower layer)?

I have my `bar {...}` config before `exec swaync`.

**Comment by ErikReider** [comment]
@tukusejssirs you can change the layer in the waybar config. Sway positions new windows behind all other surfaces with the same layer so that means that waybar is started after swaync. I've got my waybar started through the built in "bar" setting in my sway config which runs before any exec

**Comment by tukusejssirs** [comment]
Aaargh, right, so you mean you already solved the issue by changing the `layer` config in Waybar config (not the one in Sway config).

I haven’t changed `layer` (I don’t have it in my Waybar config), therefore it defaults to `bottom`.

Sorry for the noise, everyone. ;)

**Comment by ajboni** [comment]
Just to confirm, I've checked my waybar config and indeed I have that `"layer": "top"` setting applied. Glad you have it sorted @tukusejssirs
