### ISSUE TITLE
[Feature Request] Add `desktop-entry` as a regex matching filed for rules to help Flatpak users

### ISSUE THREAD

**Issue by StayPirate** [ErikReider/SwayNotificationCenter#218]
I've been using swaync for a year now. I recently switched most of the application I use to Flatpak (Firefox, Telegram-Desktop, Spotify, etc).

Suddenly I find out that Flatpak do not return `app-name`, which in turn broke all my rules. But, I noticed that `desktop_entry` is always populated.

Here is an example of notifications sent by Telegram:

 * **Flatpaked** Telegram-Desktop
 ```
category:                (null)
image_data:              true
expire_timeout:          -1
replaces_id:             0
desktop_entry:           org.telegram.desktop
body:                   test
app_icon:
action_icons:            false
time:                   1676917056
hints:
        image-data: data
        urgency: byte 0x02
        desktop-entry: 'org.telegram.desktop'
applied_id:              1
image_path:              (null)
app_name:
summary:                 📅 Reminder
icon_data:               false
resident:                false
default_action:          (null)
actions:
urgency:                 Critical
```

 * Telegram-Desktop installed via packet manager
```
category:                im.received
image_data:              true
expire_timeout:          -1
replaces_id:             0
desktop_entry:           org.telegram.desktop
body:                   È pronto
app_icon:
action_icons:            false
time:                   1676917500
hints:
        image-data: data
        desktop-entry: 'org.telegram.desktop'
        category: 'im.received'
applied_id:              3
image_path:              (null)
app_name:                Telegram Desktop
summary:                 Susy
icon_data:               false
resident:                false
default_action:          (null)
actions:
        Name: Mark as read, Id: mail-mark-read
        Name: Reply, Id: mail-reply-sender
urgency:                 Low
```

I would then ask if you can allow users to also match rules via `desktop-entry` other than `app-name`.

Nevertheless, something weird is going on in my setup. I have two computers, one running Manjaro and the other one Archlinux. On both I installed Sway and run Spotify from Flatpak, but in one I get the `app-name` populated and the other one don't.

 * Flatpaked Spotify installed on Archlinux:
```category:                (null)
image_data:              true
expire_timeout:          -1
replaces_id:             0
desktop_entry:           com.spotify.Client
body:                   Merge of Equals - Intoxicating
app_icon:
action_icons:            false
time:                   1676923307
hints:
        image-data: data
        urgency: byte 0x00
        desktop-entry: 'com.spotify.Client'
applied_id:              1
image_path:              (null)
app_name:
summary:                 Clear Blue Sky
icon_data:               false
resident:                false
default_action:          (null)
actions:
urgency:                 Low
```

 * Flatpaked Spotify installed on Manjaro:
```category:                (null)
image_data:              true
expire_timeout:          -1
replaces_id:             2
desktop_entry:           (null)
body:                   Merge of Equals - Intoxicating
app_icon:
action_icons:            false
time:                   1676923307
hints:
        image-data: data
        urgency: byte 0x00
        icon_data: data
        sender-pid: int64 6
applied_id:              2
image_path:              (null)
app_name:                Spotify
summary:                 Clear Blue Sky
icon_data:               false
resident:                false
default_action:          (null)
actions:
urgency:                 Low
```

I do not understand the reason behind this different behavior. On both I've installed `xdg-desktop-portal-wlr` and `xdg-desktop-portal`. Could you help me to debug this?

Flatpaked Firefox also doesn't return `app-name`, but `desktop-entry`:

```category:                (null)
image_data:              true
expire_timeout:          -1
replaces_id:             53
desktop_entry:           org.mozilla.firefox
body:                   ***** left home
app_icon:
action_icons:            false
time:                   1676925078
hints:
        image-data: data
        urgency: byte 0x01
        desktop-entry: 'org.mozilla.firefox'
applied_id:              1
image_path:              (null)
app_name:
summary:                 Home Presence
icon_data:               false
resident:                false
default_action:          (null)
actions:
urgency:                 Normal
```

IMO if `desktop-entry` can be used within rule filtering, any flatpaked apps would be configurable. I think that could be added as an extra option other than `app-name`.

In case there is some way to force Flatpaked apps to return `app-name` which I'm not aware of, I'd like to know it to properly configure my apps.

**Comment by StayPirate** [comment]
According to your @ErikReider comment https://github.com/ErikReider/SwayNotificationCenter/issues/26#issuecomment-958488733

> If I remember correctly, the appname/desktop_entry isn't required by the freedesktop spec so it's not guarantied that every program will send that info.

I understand that `desktop_entry` is not guaranteed to be present, so having it as an additional filter option might be a good choice.

**Comment by StayPirate** [comment]
This is probably a feature request rather than a bug, but I'm not allowed to change labels.

**Comment by ErikReider** [comment]
Adding desktop_entry should be pretty simple :)

> Nevertheless, something weird is going on in my setup. I have two computers, one running Manjaro and the other one Archlinux. On both I installed Sway and run Spotify from Flatpak, but in one I get the app-name populated and the other one don't.

This is what I get from Flatpak Spotify on Arch:

```
category:		(null)
image_data:		true
expire_timeout:		-1
replaces_id:		0
desktop_entry:		com.spotify.Client
body:			Harry Chapin - Verities & Balderdash
app_icon:		
action_icons:		false
time:			1676925984
hints:		
	image-data: data
	urgency: byte 0x00
	desktop-entry: 'com.spotify.Client'
applied_id:		4
image_path:		(null)
app_name:		
summary:		Cat's in the Cradle
icon_data:		false
resident:		false
default_action:		(null)
actions:		
urgency:		Low
```

Not sure why there's a difference between the two. The Manjaro one doesn't have a desktop_entry while having an app_name. You sure that it isn't a regular installation of Spotify?

**Comment by ErikReider** [comment]
Does the above PR work? If so, I'll merge it right a way :)

**Comment by StayPirate** [comment]
Wow that was fast! I tried it out and it works with Spotify, but not with Firefox.

The rule I'm using:
```
  "notification-visibility": {
    "no-spotify": {
      "_comment": "Don't show Spotify panel",
      "state": "ignored",
      "urgency": "Low",
      "desktop-entry": "com.spotify.Client"
    },
    "slack-show-only": {
      "_comment": "Show Slack messages but do not add them to the CC",
      "state": "transient",
      "urgency": "Low",
      "desktop-entry": "org.mozilla.firefox",
      "summary": "New message (in|from) .*"
    }
  }
```

Two notifications I got:

```
category:                (null)
image_data:              false
expire_timeout:          -1
replaces_id:             0
desktop_entry:           org.mozilla.firefox
body:                   pong
app_icon:
action_icons:            false
time:                   1676966810
hints:
        urgency: byte 0x01
        desktop-entry: 'org.mozilla.firefox'
applied_id:              1
image_path:              (null)
app_name:
summary:                 New message from Name Surname
icon_data:               false
resident:                false
default_action:          (null)
actions:
urgency:                 Normal
```
```
category:                (null)
image_data:              true
expire_timeout:          -1
replaces_id:             0
desktop_entry:           com.spotify.Client
body:                   Merge of Equals - Intoxicating
app_icon:
action_icons:            false
time:                   1676967436
hints:
        image-data: data
        urgency: byte 0x00
        desktop-entry: 'com.spotify.Client'
applied_id:              4
image_path:              (null)
app_name:
summary:                 Clear Blue Sky
icon_data:               false
resident:                false
default_action:          (null)
actions:
urgency:                 Low
```

The Spotify rule works and the notification is correctly ignored, but the Firefox one doesn't. I tried to do a bunch of tests:
- escaping dots
- removing the summary regex
- change state from transient to ignored

but I cannot manage to make it work. Do you spot any mistake on my configuration?

**Comment by StayPirate** [comment]
I now tested with flatpaked Telegram-Desktop as well and it doesn't work, same behavior as Firefox (I think).

Rule:
```
    "telegram-desktop": {
      "_comment": "Show telegram-desktop messages",
      "urgency": "normal",
      "desktop-entry": "org.telegram.desktop"
    }
```
Notification:
```
category:                (null)
image_data:              true
expire_timeout:          -1
replaces_id:             0
desktop_entry:           org.telegram.desktop
body:                   asd
app_icon:
action_icons:            false
time:                   1676968476
hints:
        image-data: data
        urgency: byte 0x02
        desktop-entry: 'org.telegram.desktop'
applied_id:              1
image_path:              (null)
app_name:
summary:                 📅 Reminder
icon_data:               false
resident:                false
default_action:          (null)
actions:
urgency:                 Critical
```

Just to be clear: swaync shows the notification, but not in the way as it should be according to the defined rules. For instance, Telegram-Desktop notifications are shown with Critical urgency instead of Normal.

**Comment by ErikReider** [comment]
> Wow that was fast! I tried it out and it works with Spotify, but not with Firefox.
> 
> The rule I'm using:
> 
> ```
>   "notification-visibility": {
>     "no-spotify": {
>       "_comment": "Don't show Spotify panel",
>       "state": "ignored",
>       "urgency": "Low",
>       "desktop-entry": "com.spotify.Client"
>     },
>     "slack-show-only": {
>       "_comment": "Show Slack messages but do not add them to the CC",
>       "state": "transient",
>       "urgency": "Low",
>       "desktop-entry": "org.mozilla.firefox",
>       "summary": "New message (in|from) .*"
>     }
>   }
> ```

**Comment by ErikReider** [comment]
How did I manage to accidentally flick the mouse onto the "close with comment" button????.... Sorry

**Comment by ErikReider** [comment]
What I was gonna say was, the `state` field isn't valid in the scripting object but that shouldn't affect the logic. The reason for why the script isn't being run is that `urgency` is set to "Low" while the notification is "Notmal"

**Comment by ErikReider** [comment]
To override the urgency, you'd need to use the `notification-visibility` setting

**Comment by StayPirate** [comment]
Amazing, the following config works as expected. Thank you very much!

```json
  "notification-visibility": {
    "no-spotify": {
      "_comment": "Don't show Spotify panel",
      "state": "ignored",
      "override-urgency": "low",
      "desktop-entry": "com.spotify.Client"
    },
    "slack-transient": {
      "_comment": "Show Slack messages but do not add them to the CC",
      "_comment": "Slack on Firefox doesn't send the signal to remove read notifications",
      "_comment": "which lead to have a overcrowded notification center. So transiet.",
      "state": "transient",
      "override-urgency": "low",
      "summary": "New message (in|from) .*",
      "desktop-entry": "org.mozilla.firefox"
    },
    "telegram-desktop": {
      "_comment": "Show telegram-desktop messages",
      "override-urgency": "normal",
      "desktop-entry": "org.telegram.desktop"
    }
  },

  "scripts": {
    "_comment": "From swaync(5): Only the first matching script is ran",
    "_comment": "In order to sort rules letters need to be used, digits don't work. So, AA is loaded before AB.",
    "AA-slack-sound": {
      "_comment": "Play a notification sounds for Slack notification from FF",
      "exec": "slack-notification-alert",
      "desktop-entry": "org.mozilla.firefox",
      "summary": "New message (in|from) .*"
    }
  }
```
