### ISSUE TITLE
[Feature Request] Ability to hide/display DND widget

### ISSUE THREAD

**Issue by phwelo** [ErikReider/SwayNotificationCenter#22]
I believe that you could simply wrap these lines in a conditional to accomplish this (as an init config item):

https://github.com/ErikReider/SwayNotificationCenter/blob/978f20de5f391ecc845844956b35be6f7f9b0969/src/controlCenter/controlCenter.vala#L186-L199

**Comment by ErikReider** [comment]
Interesting. Maybe having something similar to what waybar has in their config would work better for future buttons. Maybe create a custom button? 🤔

**Comment by phwelo** [comment]
that would be awesome to make it extensible
