### ISSUE TITLE
top-action-title in css has no effect

### ISSUE THREAD

**Issue by gabm** [ErikReider/SwayNotificationCenter#222]
**Describe the bug**

 The text in "Notifications" has very low contrast. I tried to fix that. So I went to `style.css` and fiddled with the settings, but it does not seem to be applied properly in this case. To test, I tried the following setting without visible change:

```css
.top-action-title {
  color: red;
  text-shadow: none;
}
```

Other fields like `.widget-title.color` seem to work (I can set them to red for example).

**Screenshots**

![image](https://user-images.githubusercontent.com/482105/220537990-69eee200-8261-4764-9eff-58f69df1e0da.png)

**Desktop (please complete the following information):**
 - OS: arch linux
 - Version: swaync 0.7.3 (git-4b00c96, branch 'main')

**Comment by ErikReider** [comment]
Oh right! I forgor to remove that when I switched to using configurable widgets...

The classes for those are `.widget-title` and `.widget-dnd`. I'll remove it from the default config
