### ISSUE TITLE
minimum version requirement for gtk-layer-shell

### ISSUE THREAD

**Issue by kamiyaa** [ErikReider/SwayNotificationCenter#225]
Compiles properly with gtk-layer-shell 0.8.0,
but fails with gtk-layer-shell 0.1.0:

```
../src/notificationWindow/notificationWindow.vala:40.18-40.43: error: The name `is_supported' does not exist in the context of `GtkLayerShell' (gtk-layer-shell-0)
   40 |             if (!GtkLayerShell.is_supported ()) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/controlCenter/controlCenter.vala:41.18-41.43: error: The name `is_supported' does not exist in the context of `GtkLayerShell' (gtk-layer-shell-0)
   41 |             if (!GtkLayerShell.is_supported ()) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/blankWindow/blankWindow.vala:33.18-33.43: error: The name `is_supported' does not exist in the context of `GtkLayerShell' (gtk-layer-shell-0)
   33 |             if (!GtkLayerShell.is_supported ()) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
Compilation failed: 3 error(s), 0 warning(s)
```

Perhaps we should add a minimum requirement for gtk-layer-shell dependency in meson.build?

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Version: c29bb84109c2a905d44b42ca9ff8e7951023f60a

**Comment by ErikReider** [comment]
I think some Debian release a while ago didn't ship with the latest lib. I'll check tomorrow if that's still the case

**Comment by ErikReider** [comment]
The issue here is that Ubuntu and Debian don't ship a recent GtkLayerShell version which includes a .vapi file. Without it, it's not possible to check the version. More info about it [here](https://github.com/mesonbuild/meson/discussions/9726#discussioncomment-1806366). I'll be able to check the version once those packages are updated :)

The `is_supported` function is available on Ubuntu and Debian so should be fine until then :)

**Comment by ErikReider** [comment]
Pressed the wrong button... 😅

**Comment by ErikReider** [comment]
With the GTK4 port, this will be possible :)

**Comment by Sendan4** [comment]
using GtkLayerShell development package version 0.8.1-2 on fedora 39. I can't compile it because of this error.

**Comment by ErikReider** [comment]
> using GtkLayerShell development package version 0.8.1-2 on fedora 39. I can't compile it because of this error.

I can compile it on Fedora 39 with the same version, so open a new issue :)
