### ISSUE TITLE
[Feature] Option to open as normal window?

### ISSUE THREAD

**Issue by Selmer443** [ErikReider/SwayNotificationCenter#227]
I was wondering if it was possible to allow swaync to open as a "regular" window in the config, as i'm writing this I realized I could try to force it in my compositor config (hyprland). However this would be a neat workaround for animations when the overlay is toggled. Wofi has this option which allows the program to open as a "normal" window, which allows for a bit more flexibility from the compositor. Thanks!

**Comment by ErikReider** [comment]
Are you only referring to the Control Center or the Notification popup window?

**Comment by ErikReider** [comment]
Should be easy to add (knock on wood). I'll look into it when I have time :)
