### ISSUE TITLE
[Feature Request] don't display missing icons

### ISSUE THREAD

**Issue by james-lawrence** [ErikReider/SwayNotificationCenter#23]
plenty of notifications don't have icons.

**Comment by james-lawrence** [comment]
mmm my understanding is that images and icons are [optional not required](https://specifications.freedesktop.org/notification-spec/latest/ar01s05.html). I know when I personally send notifications they mostly never contain an icon.

but yeah config switch is perfectly fine to me. =)

**Comment by ErikReider** [comment]
Oh. I must have misinterpreted the spec. Fixed in e5b1579e08d8c18ddf2204534ea89e0b899c00c5
