### ISSUE TITLE
[Bug] SwayNC crashes when reloading with volume widget enabled

### ISSUE THREAD

**Issue by Kvn0l** [ErikReider/SwayNotificationCenter#231]
SwayNC crashes when:

1. Enable volume slider widget in settings
2. Have it working, start SwayNC
3. Open SwayNC control center
4. Reload config with swaync-client -R (having it assigned to a shortcut or whatever)
5. Close the control center
6. It'll crash and output "Assertion 'c' failed at ../pulseaudio/src/pulse/context.c:1076, function pa_context_disconnect(). Aborting." in log.

**Expected behavior**
Well... I expect that it don't crash so I can see the effectiveness of my configs more easily, and this is the only circustance that i'd found it crashing like this.

**Please provide logs if you're experiencing notification errors / bugs**
[Here](https://gist.github.com/Kvn0l/9cb456cb7d745208fa974c32e9bb31df)

**Desktop (please complete the following information):**
 - OS: Arch btw
 - WM: Hyprland
 - Version: all up-to-date

**Comment by ErikReider** [comment]
Good catch! I'll fix it right away! :)
