### ISSUE TITLE
[Feature] Toggling do not disturb should  hide foreground notifications immediately

### ISSUE THREAD

**Issue by etrnal70** [ErikReider/SwayNotificationCenter#232]
**Is your feature request related to a problem? Please describe.**
With notifications exist in the monitor, toggling DND with my keybind doesn't hide the notification immediately. Instead it waits until timeout

**Describe the solution you'd like**
Toggling DND should immediately hide / remove foreground notifications

**Describe alternatives you've considered**
Haven't thought one so far. I think other notification daemon behave the same (immediately hide the notifications)

**Additional context**
None

**Comment by ErikReider** [comment]
@etrnal70 Does #233 work as expected for you?

**Comment by etrnal70** [comment]
Yeah, it's perfect 😄
