### ISSUE TITLE
If swaync is shown when swaylock executes, everything can be read. Privacy issue. [Bug]

### ISSUE THREAD

**Issue by mrpingo** [ErikReider/SwayNotificationCenter#237]
Hello and thanks for bringing us swaync
As is mentioned in the title, swaync is shown on top of the swaylock layer showing all info in it without blurring the info. On top of that, you cannot press password because the keyboard is focused on the window, until you press Escape key and the window dissapear.

Is it my fault by a missconfigured swaync? 

**To Reproduce**
1. Show swaync window.
2. Wait until swaylock executes.
4. See the window on top of swaylock.

**Expected behavior**
SwayNC get blurred or dissapear on swaylock execution.

**Screenshots**
Just tell me if you want a screenshot of it.

**Desktop (please complete the following information):**
 - OS: Gentoo latest version.
 - SwayNC-0.7.3 (the one in guru/arch repository).
 - Swaylock-effects-1.6.4

Thanks in advance.

**Comment by ErikReider** [comment]
This is fixed if you use a recent version of swaylock-effects + sway(latest stable) which includes ext-sessionlock for locking instead of layershell

**Comment by mrpingo** [comment]
Sorry for wasting your time.

Many thanks!

**Comment by ErikReider** [comment]
> Sorry for wasting your time.
> 
> Many thanks!

No worries! Happy to help :)
