### ISSUE TITLE
Could not find widget: Controlls/Brightness [Bug]

### ISSUE THREAD

**Issue by mrpingo** [ErikReider/SwayNotificationCenter#239]
Hello!

Sorry if I missed a post regarding this, but I am having some problems initiating controlls and brightness widgets.

Starting from console you can see these messages:

```
** (swaync:2459): WARNING **: 13:09:58.673: factory.vala:39: Could not find widget: "controlls"!

** (swaync:2459): WARNING **: 13:09:58.673: factory.vala:39: Could not find widget: "brightness"!
```

Did I missconfigured anything? or is it related to any compilation time flag that I missed?

**Comment by diggit** [comment]
Which widgets are you attempting to use?
There is `backlight` widget, not `brightness`
I could not find any summary of widgets, but you can use json schema to get the idea: https://github.com/ErikReider/SwayNotificationCenter/blob/main/src/configSchema.json

**Comment by mrpingo** [comment]
You are totally right! I did a mess in this file. Now everything is fixed and brightness bar works perfectly, but I am having a hard time configuring a "menubar", can anyone provide an example with the piece of config for "menubar"?

Many thanks!

PS: also I am going to close this issue.

**Comment by diggit** [comment]
Have a look here https://github.com/ErikReider/SwayNotificationCenter/discussions/183
People are sharing their configs and some probably use menubar widget.

**Comment by mrpingo** [comment]
Many thanks! Yay! After reading that, I finished with a config that I feel most confortable.

Thanks everyone!
