### ISSUE TITLE
Action button is scrollable

### ISSUE THREAD

**Issue by diggit** [ErikReider/SwayNotificationCenter#243]
**Describe the bug**
If notification has some action, button is too high and thus is scrollable. Could be some simple CSS issue, but I am not sure how to fix it.

**To Reproduce**
1. Start swaync 0.8.0 with default config
2. Send notification with action (usb guard, dunstify,...)

**Expected behavior**
Button is fully visible and thus is not scrollable

**Screenshots**
![scrolled_default](https://user-images.githubusercontent.com/512025/230769019-10b277ae-3ce8-4a0e-b9a3-5cd40c2967c8.png)
![scrolled_alt](https://user-images.githubusercontent.com/512025/230769059-ab243dec-2194-4d34-898e-815975c71a24.png)

**Desktop (please complete the following information):**
 - OS: Archlinux (up to date)
 - sway from git

**Comment by diggit** [comment]
Looks like it's GTK3 theme dependent.
with Adwaita, there no scrolling
Problematic theme sets:
- Material-black-coloer https://sourceforge.net/projects/archbangretro/
- Plata https://gitlab.com/tista500/plata-theme
- Midnight https://github.com/i-mint/midnight

I guess we have to override some GTK theme inherited CSS property...

**Comment by ErikReider** [comment]
Thanks for looking into it! Custom themes are a bit annoying due to how they override some settings and break application custom CSS... Have you found what property is causing this behavior?

**Comment by ErikReider** [comment]
I'll close this as I sadly can't support all third-party GTK themes. I've added a note to the README in 9b3c147e
