### ISSUE TITLE
[Feature] Option to disable the parsing of 2FA Security Codes?

### ISSUE THREAD

**Issue by darvs** [ErikReider/SwayNotificationCenter#244]
**Is your feature request related to a problem? Please describe.**
The body of most of my notifications contains a year. This is recognized as a 2FA Security Code and thus an action button is automatically added with the option to `COPY "2023"` to the clipboard which is not useful to my use case.

**Describe the solution you'd like**
I would like an option to disable the parsing of security codes. Maybe offer the option to enable/disable this per app-name?

**Describe alternatives you've considered**
I've looked at the code in pull [#217](https://github.com/ErikReider/SwayNotificationCenter/pull/217) but didn't find a way to skip that check.

Thank you for your time.

**Comment by ErikReider** [comment]
I'll look into it. Can't promise it'll be soon though so a PR would be appreciated :)

**Comment by darvs** [comment]
Ok. In that case leave it to me for now. I'll try to submit a PR soon and we can have a look at it together then.
