### ISSUE TITLE
[Feature] Dismiss notification when focusing the source application

### ISSUE THREAD

**Issue by gabm** [ErikReider/SwayNotificationCenter#247]
Similar to android/ios it might be useful to dismiss the notifications, when focusing the source application. Two example workflows

1. I am working in an application. An Email arrives and I get a notification from Thunderbird. I focus Thunderbird to read the mail -> the notification disappears automatically.
2. I am working in an application. A chat message arrives in my browser. I focus firefox to read it -> notification disappears automatically.

Currently I have to manually go through the notifications and clear them - even though I already acted on them.

**Comment by ErikReider** [comment]
It's the applications job to dismiss it's notifications on focus. Discord currently does this.

If you have any more questions/feedback/issues, be sure to open a discussion/another issue :)
