### ISSUE TITLE
[Bug] swaync won't respect order of rules for visibility

### ISSUE THREAD

**Issue by diesphink** [ErikReider/SwayNotificationCenter#255]
**Describe the bug**

swaync won't respect order of rules for visibility: at loading time the rules get in random (unexpected, but consisting) order.
The order seems to be based on the name used for each rule.

**To Reproduce**

Configure a few notification-visibility rules, but one of them will always run if nothing else executes.

For example, from my cfg:

```json
"notification-visibility": {
  "1-power-status": {
    "state": "transient",
    "app-name": "poweralertd"
  },
  "2-hud-messages": {
    "state": "transient",
    "category": "hud"
  },
  "3-everything-else": {
    "state": "muted",
    "summary": ".*"
  }
},
```

Every notification is getting muted, instead of just the notifications that the first two rules didn't catch.

**Expected behavior**

Notifications either from app-id poweralertd or with category hud should be transient, everything else should be muted.

**Please provide logs if you're experiencing notification errors / bugs**

When I run swaync with debug I can see the order that it's loading from the file, the example above becomes:

```json
"notification-visibility" : {
  "3-everything-else" : {
    "summary" : ".*",
    "state" : "muted"
  },
  "1-power-status" : {
    "app-name" : "poweralertd",
    "state" : "transient"
  },
  "2-hud-messages" : {
    "category" : "hud",
    "state" : "transient"
  }
},
```

As the 3-everything-else is the first one, it explains the behavior.

If I change some of the names (in the case below, added ! at the end of the second rule name), I can randomly change the order:

```json
"notification-visibility" : {
  "2-hud-messages!" : {
    "category" : "hud",
    "state" : "transient"
  },
  "3-everything-else" : {
    "summary" : ".*",
    "state" : "muted"
  },
  "1-power-status" : {
    "app-name" : "poweralertd",
    "state" : "transient"
  }
},
```

The one that eventually worked in the order that I wanted was adding ! to the third rule:

```json
"notification-visibility" : {
  "1-power-status" : {
    "app-name" : "poweralertd",
    "state" : "transient"
  },
  "2-hud-messages" : {
    "category" : "hud",
    "state" : "transient"
  },
  "3-everything-else!" : {
    "summary" : ".*",
    "state" : "muted"
  }
},
```

**Desktop (please complete the following information):**

OS: Ubuntu Sway 23.04 x86_64 
DE: sway (Wayland)
swaync: 0.7.3

**Additional context**
Json libs won't always keep the order of properties of an object, and it might be the case here. As it's based on name, seems to be using hashmap internally.

If that's the case, my suggestion is either using an array as example 1 below (my personal preference), adding order to each rule object as example 2 below, or ordering the rules by name.

Exampele 1
```json
"notification-visibility" : [
  {
    "app-name" : "poweralertd",
    "state" : "transient"
  },
  {
    "category" : "hud",
    "state" : "transient"
  },
  {
    "summary" : ".*",
    "state" : "muted"
  }
],
```

```json
"notification-visibility" : {
  "power-status" : {
    "order": 1,
    "app-name" : "poweralertd",
    "state" : "transient"
  },
  "hud-messages" : {
    "order": 2,
    "category" : "hud",
    "state" : "transient"
  },
  "everything-else!" : {
    "order": 3,
    "summary" : ".*",
    "state" : "muted"
  }
},
```

**Mandatory compliment**
Great software, by the way! Thanks for your work.

**Comment by ErikReider** [comment]
Switching to an array would break peoples configs which isn't ideal. I have a fix in the works for the ordering by just adding the keys into a linked list :)

**Comment by ErikReider** [comment]
#258 fixes the issue on my end but does it fix it for you?

**Comment by diesphink** [comment]
Thank you for the quick fix, I'm using the version from repo, but I'll compile with that change later today and let you know.

**Comment by diesphink** [comment]
#258 works for me
