### ISSUE TITLE
[Bug] SwayNC is displayed above fullcreen windows despite `layer=top`

### ISSUE THREAD

**Issue by cinghiopinghio** [ErikReider/SwayNotificationCenter#256]
**Describe the bug**
As per the title, swaync notifications are displayed above fullscreen windows both in sway and hyprland.

**To Reproduce**
0. set `layer=top` in the configuration file (reload config if necessary)
1. get a window fullscreen
2. send a notification
3. bam

**Expected behavior**
Notification is not displayed.

**Please provide logs if you're experiencing notification errors / bugs**
Debug messaged of regular notification and notification over a fullscreen window do not change (except for the id).

**Screenshots**
In the image, from a fullscreen terminal I send a notification that get displayed above the fullscreen terminal.

![image](https://github.com/ErikReider/SwayNotificationCenter/assets/1894436/e87264eb-3321-4703-acf3-e867e8390a40)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version latest

**Comment by ErikReider** [comment]
>  0. set layer=top in the configuration file (reload config if necessary)

Is this a typo? Should be in a JSON format

**Comment by cinghiopinghio** [comment]
Here you can find my config (that was a typo indeed):
``` json
{
    "$schema": "/etc/xdg/swaync/configSchema.json",
    "positionX": "right",
    "positionY": "top",
    "layer": "top",
    "cssPriority": "application",
    "control-center-margin-top": 0,
    "control-center-margin-bottom": 0,
    "control-center-margin-right": 0,
    "control-center-margin-left": 0,
    "notification-icon-size": 64,
    "notification-body-image-height": 100,
    "notification-body-image-width": 200,
    "timeout": 10,
    "timeout-low": 5,
    "timeout-critical": 0,
    "fit-to-screen": true,
    "control-center-width": 500,
    "control-center-height": 600,
    "notification-window-width": 500,
    "keyboard-shortcuts": true,
    "image-visibility": "when-available",
    "transition-time": 200,
    "hide-on-clear": false,
    "hide-on-action": true,
    "script-fail-notify": true,
    "widgets": [
        "inhibitors",
        "title",
        "dnd",
        "backlight",
        "volume",
        "mpris",
        "notifications"
    ],
    "widget-config": {
        "inhibitors": {
            "text": "Inhibitors",
            "button-text": "Clear All",
            "clear-all-button": true
        },
        "title": {
            "text": "Notifications",
            "clear-all-button": true,
            "button-text": "Clear All"
        },
        "dnd": {
            "text": "Do Not Disturb"
        },
        "label": {
            "max-lines": 5,
            "text": "Label Text"
        },
        "mpris": {
            "image-size": 96,
            "image-radius": 12
        },
        "backlight": {
            "label": "Brightness: ",
            "device": "intel_backlight",
            "min": 5
        },
        "volume": {
            "label": "Volume: "
        }
    }
}

```

**Comment by ErikReider** [comment]
What's the output of swaync? Run like this `G_MESSAGES_DEBUG=all swaync`

**Comment by ErikReider** [comment]
Oh wait! Are you referring to the notifications or the control center? The control center is the only one affected by the `layer` config option

**Comment by cinghiopinghio** [comment]
You are right. I'm referring to the notification itself, not the control center (as in the picture above).

**Comment by ErikReider** [comment]
I totally misunderstood your issue 😅

The PR should fix this bug and adds a `control-center-layer` option
