### ISSUE TITLE
Scripting supported

### ISSUE THREAD

**Issue by ldelossa** [ErikReider/SwayNotificationCenter#26]
Hey there, 

With dunst Im able to script actions for specific notifications. 

Is this possible with SwayNotificationsCenter?

**Comment by ErikReider** [comment]
When they are displayed or clicked on?

Notifications can provide different actions that are in this case displayed as clickable GTK Buttons. The default action is mapped to the top button (with the title and body).

![image](https://user-images.githubusercontent.com/35975961/139740062-bd255c78-5859-4297-ac25-6f95b2996367.png)

**Comment by ldelossa** [comment]
@ErikReider when they are received from by the daemon. 

for instance, when a Spotify event is received by dunst, I inform it to run a script. This script sends a signal to Waybar and updates my custom Spotify widget. 

Here's the docs I've used: https://wiki.archlinux.org/title/Dunst

I like this project, but would need a similar feature to move over (not pushing you to do it or not, you may hate this idea)

**Comment by ErikReider** [comment]
@ldelossa Sounds interesting :)

Could you share your config here as a comment? It would be interesting to see how they check which notification is from which application. I guess that they're using some basic regex matching

**Comment by ldelossa** [comment]
Here's my config:

https://github.com/ldelossa/dotfiles/tree/master/config/dunst

relevant bits are:
https://github.com/ldelossa/dotfiles/blob/a20e9ebb706efc5fdd27310c17ca01bb2cd305c3/config/dunst/dunstrc#L351

https://github.com/ldelossa/dotfiles/blob/master/config/dunst/spotify-event.sh

**Comment by ldelossa** [comment]
My hunch is it's regexp matching as well.

**Comment by ErikReider** [comment]
This is interesting. They can match the appname. If I remember correctly, the appname/desktop_entry isn't required by the freedesktop spec so it's not guarantied that every program will send that info. Spotify sends that info right?
```
# Messages can be matched by
#    appname (discouraged, see desktop_entry)
#    body
#    category
#    desktop_entry
#    icon
#    match_transient
#    msg_urgency
#    stack_tag
#    summary
```

**Comment by ldelossa** [comment]
@ErikReider Spotify is a bad example, the flatpak is broken and sends no info. There's an RPM that you can find which does send that info, but its still not great.

**Comment by ErikReider** [comment]
I'll look into this :)

**Comment by mpldr** [comment]
Just my two cents: One way would be to create a link from `/usr/bin/notify-send` => `/usr/bin/swaync-client`. Calls to `notify-send` – the de-facto standard for everything notification-related – could be detected by checking `argv[0]` and then provide the usual CLI: https://man.archlinux.org/man/notify-send.1

**Comment by ErikReider** [comment]
> Just my two cents: One way would be to create a link from `/usr/bin/notify-send` => `/usr/bin/swaync-client`. Calls to `notify-send` – the de-facto standard for everything notification-related – could be detected by checking `argv[0]` and then provide the usual CLI: https://man.archlinux.org/man/notify-send.1

This issue is about running scripts when a notification is shown from a specific application. Thanks for your two cents though :)

**Comment by mpldr** [comment]
Ahh, sorry I misunderstood. I'll put this into a new issue.

**Comment by nightly-brew** [comment]
We could have a matcher function run on each new notification, after it has been added to the relevant panels and sound has been played (so it doesn't clog the most important actions of the daemon) that iterates a list of match-script objects.

**Comment by ErikReider** [comment]
> I've never written scripts to run from dunst, but I suppose having two script with the same match parameters should mean both are ran, right?

I guess so? I haven't done this either so I'm kinda clueless

**Comment by ldelossa** [comment]
Yes, both are ran.

**Comment by ErikReider** [comment]
Should now work! :)

**Comment by ldelossa** [comment]
Any docs on how to test this out?

**Comment by ErikReider** [comment]
Check the README

**Comment by ldelossa** [comment]
Just moved over to this, removed Dunst, everything working great so far, and looks so much better! Thanks for the efforts here.
