### ISSUE TITLE
[issue] Swaync only works on one test site

### ISSUE THREAD

**Issue by hajosattila** [ErikReider/SwayNotificationCenter#265]
I have a noob question regarding Swaync. I'm using Sway WM on Arch Linux, and for some reason ([except for one test site](https://www.bennish.net/web-notifications.html)) the notification doesn't work with Firefox (Gmail, Reddit... nothing)

The test site works perfectly, which leads me to believe that the problem is not with swaync.

[link](https://imgur.com/a/a71xAU9)

Also, it's not completely clear to me how to configure, for example, that when Tidal Webplayer changes tracks, it should notify.

If you could give me some example configs (scripts) as a starting point, I would be very happy.

e.g.:

- Gmail

- Tidal

- qBittorrent Web UI

- xy Bluetooth connected

...etc

Sorry for my English!

**Comment by hajosattila** [comment]
ohh wait, Discord is working!!!!

![scrn-2023-05-16-21-35-13](https://github.com/ErikReider/SwayNotificationCenter/assets/1567493/9a006122-495a-4868-916d-dcf8c62894fc)

**Comment by ErikReider** [comment]
The defaults are enough for a usable experience. Most of the config options are just customization.

If one website works and not the others, it's not swaync:s problem. Make sure that you've given the websites permission to display notifications in Firefox :)

**Comment by hajosattila** [comment]
Working flawlesly :) I'm so happy with it :D

![scrn-2023-05-16-22-35-59](https://github.com/ErikReider/SwayNotificationCenter/assets/1567493/3146c7d0-e0f6-453a-88b2-6a617c1a8514)

**Comment by Sohail-XD** [comment]
ohh wait, Discord is working!!!!
> 
> ![scrn-2023-05-16-21-35-13](https://user-images.githubusercontent.com/1567493/238753687-9a006122-495a-4868-916d-dcf8c62894fc.png)

How did you get it to work?
