### ISSUE TITLE
Trigger reload of style.css

### ISSUE THREAD

**Issue by ma-con** [ErikReider/SwayNotificationCenter#27]
I just tried swaync and I quite like it so far.

However I have one question / request:
I use flavours (https://github.com/Misterio77/flavours/) to inject base16 color schemes in the `style.css` of swaync which works fine. However, in order for the changed colors to be applied, I have to kill and restart swaync. 

Would it be possible to live-reload `style.css`, like it can be done with `swaync-client -R` for the config file?

Thanks for your effort!

**Comment by ErikReider** [comment]
Sounds interesting. I'd have to load the css file again but does GTK override the old loaded css or just apply it over? I'll have to experiment :)

**Comment by ErikReider** [comment]
baab0cd9b8bfa442ea6789d2a1f75480a264ac62 Should work now. You can reopen/comment here if there are any issues :)

**Comment by ma-con** [comment]
Awesome, thank you very much!
I just tested it and it works really great. I just discovered one minor problem:
If the css reload happens when the notification center is not shown, notifications that have been there before are not restyled.

For example: Here I switched from light to dark mode without the notification center being open:
![nc-light](https://user-images.githubusercontent.com/3628261/142397239-ac8547a6-4ac6-447f-b1a0-76eb381bc6e5.png)
![nc-dark](https://user-images.githubusercontent.com/3628261/142397249-77f3ce0e-b1b5-468f-bc45-562c278fbe8f.png)
 
And this is how it should look like in dark mode:
![nc-dark-correct](https://user-images.githubusercontent.com/3628261/142397314-f17a84f4-b839-4347-b6be-a065e9cc6059.png)

The correct colors are applied when the switch happens if the panel is open, or once I hover over the notifications.

**Comment by ErikReider** [comment]
That's strange... I'll check it out

**Comment by ErikReider** [comment]
This is a weird bug. Seems to only affect the control center

**Comment by ErikReider** [comment]
This seems to be a GTKLayerShell issue

**Comment by ErikReider** [comment]
Hmmmm. Seems that the eventbox isn't updating it's color...

**Comment by ErikReider** [comment]
afefe58cba7fcf3324c1b456fa73ec17027f55d5 should fix this :)

**Comment by xircon** [comment]
Using the current git version from aur.  If I reload config it is not reloading the CSS - what am I misunderstanding?

**Comment by ErikReider** [comment]
> Using the current git version from aur.  If I reload config it is not reloading the CSS - what am I misunderstanding?

There's a separate command for reloading the CSS

**Comment by xircon** [comment]
I will book a trip to the opticians.
