### ISSUE TITLE
[Feature] Make pulseaudio optional

### ISSUE THREAD

**Issue by freijon** [ErikReider/SwayNotificationCenter#271]
With 0.8.0 some pulseaudio features were added, which is great! At least for most people... I'm packaging this application for the Gentoo Linux Distribution. As you may know, Gentoo allows the user to enable/disable certain features at compile time. We made the pulseaudio stuff an optional feature because of the (quite heavy) pulseaudio dependency and we'd like to offer this application also to users who decided to use a different sound server.

That's why I'm asking to have an option to enable/disable the pulseaudio feature via the `meson_options.txt`. Since 0.8.0 we have to maintain a quite substantial patch to remove everything pulseaudio related. Having this as an optional feature would be very helpful :)

I'm interested to learn what you think about this idea.

**Comment by ErikReider** [comment]
That sounds like a reasonable request :)

How high of a priority is this?

**Comment by freijon** [comment]
I see you added this to the v1.0.0 milestone 👍 Depends how many releases you plan until then. We're all set now for v0.9.0, so no issue there. But for every release I have to figure out what to patch out. This gets more complex the more the pulseaudio code base grows. It takes some time and I might miss something. Of course I always check if the patched code compiles, but there might be other stuff, e.g. in the man pages or in the help that I miss. So I guess the sooner the better from my point of view ;)
