### ISSUE TITLE
Notification window cut off on the bottom

### ISSUE THREAD

**Issue by itm154** [ErikReider/SwayNotificationCenter#274]
Any fix for this? Looks like they are no option for the window height for now (#174). Only happens with notification with interactions.
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/67090166/a8c32be0-5921-43d4-b9ec-6e1e752a09c8)

**Comment by ErikReider** [comment]
Try using the default css + using adwaita gtk theme

**Comment by itm154** [comment]
Works as expected. But I assume this is just a temporary fix since I can't use my gtk theme

![2023-06-05-211422_grim](https://github.com/ErikReider/SwayNotificationCenter/assets/67090166/2231540c-6cd3-48b3-8cee-e1ccb7d3d420)

**Comment by ErikReider** [comment]
As I've written in the README, it's impossible for me to test every GTK3 theme out there, so the default Adwaita/adw-gtk3 theme is the only theme that I've tested. Other themes might require tweaking the default SwayNC CSS file. :/

Glad that it's "fixed" If there's anything else, open a discussion thread :)

**Comment by ErikReider** [comment]
Fixed by #561
