### ISSUE TITLE
covers (mpris)

### ISSUE THREAD

**Issue by Manix80** [ErikReider/SwayNotificationCenter#310]
as described in the title, I don't have the album covers in the mpris module, but they do appear in the notifications.
nothing similar found on the net or there: https://github.com/ErikReider/SwayNotificationCenter/pull/157

I use this configuration: https://github.com/ErikReider/SwayNotificationCenter/discussions/183?sort=old#discussioncomment-4627181 @JannisPetschenka

Hyprland with arch and player ncspot. do I need a complement like uberzug++ or something else?
thank you for your work!

**Comment by ErikReider** [comment]
It's the applications responsibility to provide a cover art so this isn't a swaync issue. Spotify and Firefox works for me :)

**Comment by sharak** [comment]
Hi!

I am having the same problem using Spotify. If I use playerctl to look at the player metadata I get this:
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/985713/6d61ae66-7fd5-4d1a-8b5d-0d298c2929ce)

Running `G_MESSAGES_DEBUG=all swaync` I get the following log:
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/985713/03070d39-7415-4ad8-8537-6c6eeb880efe)

It's as if it's trying to download the cover but can't for some reason.

**Comment by ErikReider** [comment]
> Hi!
> 
> I am having the same problem using Spotify. If I use playerctl to look at the player metadata I get this: ![image](https://user-images.githubusercontent.com/985713/284893537-6d61ae66-7fd5-4d1a-8b5d-0d298c2929ce.png)
> 
> Running `G_MESSAGES_DEBUG=all swaync` I get the following log: ![image](https://user-images.githubusercontent.com/985713/284894338-03070d39-7415-4ad8-8537-6c6eeb880efe.png)
> 
> It's as if it's trying to download the cover but can't for some reason.

Could you copy&paste the url here?

**Comment by sharak** [comment]
Sure:
https://i.scdn.co/image/ab67616d0000b273968059c0bdab66e2b558e582

However, this happens with any URL.

**Comment by ErikReider** [comment]
Seems like I'm able to download that when manually changing the `url` variable...

**Comment by ErikReider** [comment]
Could you try using this patch, run it and send me the new error message?

```diff
diff --git a/src/controlCenter/widgets/mpris/mpris_player.vala b/src/controlCenter/widgets/mpris/mpris_player.vala
index cec2322..bc5df65 100644
--- a/src/controlCenter/widgets/mpris/mpris_player.vala
+++ b/src/controlCenter/widgets/mpris/mpris_player.vala
@@ -258,8 +258,8 @@ namespace SwayNotificationCenter.Widgets.Mpris {
                     pixbuf = yield new Gdk.Pixbuf.from_stream_async (
                         stream, album_art_cancellable);
                 } catch (Error e) {
-                    debug ("Could not download album art for %s. Using fallback...",
-                           source.media_player.identity);
+                    debug ("Could not download album art for %s. Using fallback...\n\tURL: %s\n\tError: %s",
+                           source.media_player.identity, url, e.message);
                 }
                 if (pixbuf != null) {
                     pixbuf = Functions.scale_round_pixbuf (pixbuf,
```

**Comment by Manix80** [comment]
as far as i'm concerned, it's working properly now. i didn't do any manipulations. just the system updates.

**Comment by sharak** [comment]
> Could you try using this patch, run it and send me the new error message?
> 
> ```diff
> diff --git a/src/controlCenter/widgets/mpris/mpris_player.vala b/src/controlCenter/widgets/mpris/mpris_player.vala
> index cec2322..bc5df65 100644
> --- a/src/controlCenter/widgets/mpris/mpris_player.vala
> +++ b/src/controlCenter/widgets/mpris/mpris_player.vala
> @@ -258,8 +258,8 @@ namespace SwayNotificationCenter.Widgets.Mpris {
>                      pixbuf = yield new Gdk.Pixbuf.from_stream_async (
>                          stream, album_art_cancellable);
>                  } catch (Error e) {
> -                    debug ("Could not download album art for %s. Using fallback...",
> -                           source.media_player.identity);
> +                    debug ("Could not download album art for %s. Using fallback...\n\tURL: %s\n\tError: %s",
> +                           source.media_player.identity, url, e.message);
>                  }
>                  if (pixbuf != null) {
>                      pixbuf = Functions.scale_round_pixbuf (pixbuf,
> ```
Error: Operation not supported (in my main language on the screenshot)
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/985713/16b09e0d-52e3-4259-9a40-2dd25da5798b)

**Comment by ErikReider** [comment]
Do you have gvfs installed?

**Comment by sharak** [comment]
No

**Comment by ErikReider** [comment]
> No

Can you try with it installed?

**Comment by sharak** [comment]
Yes, it's works. 

Today I received an update from AUR and it included the gvfs dependency.

Thank you!

**Comment by carettt** [comment]
Hi, I am having this same issue with `gvfs` installed. `playerctl metadata` shows an `artUrl` that does work, but I am still getting the following error:
```
** (swaync:33956): DEBUG: 18:41:58.093: mpris_player.vala:335: Could not download album art for ncspot. Using fallback...
```
The `artUrl` is: https://i.scdn.co/image/ab67616d0000b2733ebc5b9d8942069d3b920550 if that helps?

**Comment by paul-ri** [comment]
Same, on Arch Linux with `swaync 0.11.0`, `gvfc` is installed. It started to fail maybe two months ago, not sure. When using [`tidal-hifi`](https://github.com/Mastermindzh/tidal-hifi/), it stalls for ~30s when starting and whenever a new track starts.

> ** (swaync:143704): DEBUG: 12:29:57.330: mpris_player.vala:335: Could not download album art for tidal-hifi. Using fallback...

Downgrading to `swaync-0.10.1-2-x86_64.pkg.tar.zst` doesn't solve it.

Removing the `mpris` widget config fixes the issue. Or using `mako` instead of `swaync` works too.

I don't know how to debug this any better yet. Happy to hear suggestions! I don't see anything that jumps out in `dbus-monitor`'s output.

**Comment by ErikReider** [comment]
> Same, on Arch Linux with `swaync 0.11.0`, `gvfc` is installed. It started to fail maybe two months ago, not sure. When using [`tidal-hifi`](https://github.com/Mastermindzh/tidal-hifi/), it stalls for ~30s when starting and whenever a new track starts.
> 
> > ** (swaync:143704): DEBUG: 12:29:57.330: mpris_player.vala:335: Could not download album art for tidal-hifi. Using fallback...
> 
> Downgrading to `swaync-0.10.1-2-x86_64.pkg.tar.zst` doesn't solve it.
> 
> Removing the `mpris` widget config fixes the issue. Or using `mako` instead of `swaync` works too.
> 
> I don't know how to debug this any better yet. Happy to hear suggestions! I don't see anything that jumps out in `dbus-monitor`'s output.

Have you tried the latest changes in the main branch?

**Comment by paul-ri** [comment]
Sadly I tried and have the same issue. `swaync --version`: `swaync 0.11.0 (git-f55b433, branch 'main')`. Output example of `G_MESSAGES_DEBUG=all swaync` after hitting the next track button on tidal-hifi:

```
** (swaync:5967): DEBUG: 11:42:19.706: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:20.677: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:20.680: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:20.680: mpris_player.vala:138: Changed: CanPlay
** (swaync:5967): DEBUG: 11:42:20.680: mpris_player.vala:138: Changed: CanPause
** (swaync:5967): DEBUG: 11:42:20.680: mpris_player.vala:138: Changed: CanGoPrevious
** (swaync:5967): DEBUG: 11:42:20.680: mpris_player.vala:138: Changed: CanGoNext
** (swaync:5967): DEBUG: 11:42:20.680: mpris_player.vala:138: Changed: PlaybackStatus
** (swaync:5967): DEBUG: 11:42:20.681: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:20.682: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:20.682: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:20.683: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:20.683: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:20.683: mpris_player.vala:267: Could not download album art for tidal-hifi. Using fallback...
** (swaync:5967): DEBUG: 11:42:20.690: mpris_player.vala:138: Changed: CanSeek
** (swaync:5967): DEBUG: 11:42:46.039: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:46.040: notiDaemon.vala:177: Notification: 
category:		(null)
image_data:		true
expire_timeout:		-1
replaces_id:		0
desktop_entry:		tidal-hifi
body:			Tiga, Hudson Mohawke
app_icon:		
action_icons:		false
time:			1750675366
hints:		
	urgency: byte 0x01
	sender-pid: int64 5999
	desktop-entry: 'tidal-hifi'
	image-data: data
applied_id:		11
image_path:		(null)
inline-reply:		(null)
app_name:		tidal-hifi
summary:		VSOD (Velvet Sky of Dreams)
icon_data:		false
resident:		false
default_action:		Name: View, Id: default
actions:		
urgency:		Normal

** (swaync:5967): DEBUG: 11:42:46.088: mpris_player.vala:138: Changed: Metadata
** (swaync:5967): DEBUG: 11:42:46.089: mpris_player.vala:138: Changed: Metadata
```
If changing track whilst swaync UI is open, the whole desktop environment is unusable as swaync is unresponsive to inputs for ~20s as it lays in front of all windows.
