### ISSUE TITLE
[Bug] missing icons for some apps

### ISSUE THREAD

**Issue by blauch** [ErikReider/SwayNotificationCenter#315]
**Describe the bug**
I am using swaync as it's part of [nwg-shell](https://github.com/nwg-piotr/nwg-shell). For some apps notifications do not show the app icons but a placeholder. For example Slack and Network Manager notifications do not have proper icons next to the message while notifications from the browser do. Please see the screenshot below

I was [sent here ](https://github.com/nwg-piotr/nwg-panel/issues/224#issuecomment-1729121923)

**To Reproduce**
1. Launch swaync with nwg-shell
2. Start Slack or Network Manager
3. wait  for notifications
4. for some apps a placeholder icon will be displayed instead of the app icon 

**Expected behavior**
All notifications have the correct app icons next to its messages

**Please provide logs if you're experiencing notification errors / bugs**
[Logs](https://gist.github.com/blauch/3119894fffe9265294cee64299e4c7cf)

**Screenshots**
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/18649280/4f5cd632-4ce1-4eec-ab38-fc88cb422aae)

**Desktop:**
 - OS: Manjaro 23.0.2
 - Version: 0.9.0-1

**Additional context**
I noticed `image_path:		(null)` in the logs

**Comment by ErikReider** [comment]
>  I noticed image_path:		(null) in the logs

Yeah, this is a application issue that I can't resolve. Swaync checks for a application icon if an icon isn't provided and uses a fallback if said icon is not found
