### ISSUE TITLE
Provide notify-send

### ISSUE THREAD

**Issue by mpldr** [ErikReider/SwayNotificationCenter#32]
One way to easily catch all notifications on a system would be to create a link from `/usr/bin/notify-send` => `/usr/bin/swaync-client`. Calls to `notify-send` – the de-facto standard for everything notification-related – could be detected by checking `argv[0]` and then provide the usual CLI: https://man.archlinux.org/man/notify-send.1

This would also allow to easily send notifications to SwayNC from scripts.

**Comment by ErikReider** [comment]
But you can already do that with `notify-send`. Why would `swaync-client` need this?

**Comment by ErikReider** [comment]
> To unify all notifications in swaync. And get rid of this rather silly situation: ![20211214_21h53m22s_grim](https://user-images.githubusercontent.com/33086936/146077827-f940efc3-a41c-48a3-9250-54b40008b23b.png)

Can you elaborate further?

**Comment by mpldr** [comment]
> Can you elaborate further?
In this case the mako notification is overlayed over the swaync notification center… I found the reason though. It seems mako still started even though I commented it out in my sway config.
