### ISSUE TITLE
cover image does not display when playing something with mpv

### ISSUE THREAD

**Issue by XxRiKxX** [ErikReider/SwayNotificationCenter#322]
I am on arch and have mpv-mpris installed. The cover image works for youtube music.
also, how can I blur the panel in hyprland?

**Comment by ErikReider** [comment]
> I am on arch and have mpv-mpris installed. The cover image works for youtube music.

This sounds like a mpv-mpris issue. Please raise an issue with their software

> how can I blur the panel in hyprland?

I'm running SwayFX so can't really tell you how to do that, you should refer to their online documentation :)
