### ISSUE TITLE
[Feature] Show specific notifications but not in the notification center

### ISSUE THREAD

**Issue by diologix** [ErikReider/SwayNotificationCenter#326]
**Please read through the README and the Man pages before submitting**
**Please also make sure that there isn't any prior issue describing this feature**

**Is your feature request related to a problem? Please describe.**
When low notifications like "Bluetooth Headphones connected" or Spotify current playing notifications are beeing send, it would be nice, to let them show as normal, but to surpress them in the notification center. So i just see them and thats it. Currently i also dont see an option to delete specific notifications with swaync-client. Otherwise i would write myself a script to control it. 

**Describe the solution you'd like**
Currently when i inhibit spotify for example, they wont be shown in the normal way but appear in the notification center. A way to configure it the other way around would be nice

**Describe alternatives you've considered**
Alternatively to delete a notification with swaync-client would also be an solution.

**Additional context**

**Comment by ErikReider** [comment]
Do you have a rule for setting Spotify notifications as low priority? Could you provide it here?

**Comment by guttermonk** [comment]
Eric Murphy talks about something similar that he made with Dunst in [this video](https://youtu.be/XWlbaERuDP4?si=W-9Q2nBq-Z7CPHMl&t=751). He uses the "changevolume" label from his script to filter out any volume change notifications. He sets a notification rule in the config under the [history-ignore] section to ignore any appname equal to changevolume.

Maybe we could do something like this in swaync?

**Comment by ErikReider** [comment]
Well using the provided `notification-visibility` property in the config:

```json
  "notification-visibility": {
    "some name":{
      "app-name": "the appid of the application",
      "state": "transient"
    }
  },
```

or using the `-e` flag with `notify-send` would fix this.

Closing :)
