### ISSUE TITLE
[Feature] Toggle buttons in menubar

### ISSUE THREAD

**Issue by AmirDahan** [ErikReider/SwayNotificationCenter#337]
**Please read through the README and the Man pages before submitting**
**Please also make sure that there isn't any prior issue describing this feature**

**Is your feature request related to a problem? Please describe.**
At the moment it seems like Toggle buttons are only applicable to button grids

**Describe the solution you'd like**
I would like for the ability to have togglable buttons in menubars

**Describe alternatives you've considered**
Manually switching the config and reloading

**Additional context**
the type [normal, toggle] seems to only apply to button grids
it would be nice to have toggle buttons in menubars

**Comment by JannisPetschenka** [comment]
Wellll, that was actually supposed to work, but I just forgot the 5 lines, that would actually do it :smile: 

#339 fixes it
