### ISSUE TITLE
[Feature] Allow to specify format (i.e. include appname in notification)

### ISSUE THREAD

**Issue by leon-erd** [ErikReider/SwayNotificationCenter#338]
**Please read through the README and the Man pages before submitting**
**Please also make sure that there isn't any prior issue describing this feature**

**Is your feature request related to a problem? Please describe.**
It would be nice for me to know which app is sending the notification. 
A notification could be coming through my phone (via KDE Connect for example) or from my computer. They could have the exact same summary and body but would have different appnames.

**Describe the solution you'd like**
I would like the option to define in my config if the appname should be shown in the notifications or not.
Or to set a markup format similar to dunst. The following is copied from the dunstrc:
    # The format of the message.  Possible variables are:
    #   %a  appname
    #   %s  summary
    #   %b  body
    #   %i  iconname (including its path)
    #   %I  iconname (without its path)
    #   %p  progress value if set ([  0%] to [100%]) or nothing
    #   %n  progress value if set without any extra characters
    #   %%  Literal %
    # Markup is allowed
    format = "<b>%s</b>\n%b\n<span size="80%">%a</span>"
    
The appname could also be used to infer an app icon like it is done in linux_notification_center which looks really nice:

![20231123_16h45m45s_grim](https://github.com/ErikReider/SwayNotificationCenter/assets/99900077/7d795fac-0ceb-4311-8f33-da72ac6154c2)
Screenshotted from the linux_notification_center README

**Additional context**
Thanks for the overall really nice program!

**Comment by ErikReider** [comment]
#61 would make it easier to identify which notifications are sent by which application

**Comment by leon-erd** [comment]
If it would look like the screenshots from cosmic (with the icon and the app name for each notification / group) that would be perfect! Really looking forward seeing this!

**Comment by leon-erd** [comment]
I have already seen the PR :) However, in the video, there are no icons/app names for single notifications yet. I'm excited to test and see the changes once the PR is ready to use.

**Comment by ErikReider** [comment]
> I have already seen the PR :) However, in the video, there are no icons/app names for single notifications yet. I'm excited to test and see the changes once the PR is ready to use.

![image](https://github.com/ErikReider/SwayNotificationCenter/assets/35975961/48993324-ff21-49d5-ba18-a923d06b94e8)
This should solve your issue :)

**Comment by leon-erd** [comment]
That looks good! But will this also be available for single notifications that are not part of a group?

**Comment by ErikReider** [comment]
> That looks good! But will this also be available for single notifications that are not part of a group?

Nope, couldn't find a way to make it look good. If you can find a nice design, I'll consider it :)

**Comment by leon-erd** [comment]
I think the Cosmic design actually looks really good and is pretty much what I am looking for.

![150807140-cf407ab8-c311-46c9-bc34-46bac0e49708](https://github.com/ErikReider/SwayNotificationCenter/assets/99900077/51c81fe4-3e43-4eb2-9a94-d209358dd76a)

I like it with the app name in a smaller font size above the bold summary. I think an option in the config to enable/disable the icon and app name would be perfect.
I also like the design of the linux_notification_center with the icon and app name in the bottom right as attached above.

**Comment by ErikReider** [comment]
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/35975961/eca8994a-0f29-48d2-b587-da5324d20c74)

This is a work in progress
