### ISSUE TITLE
XML-encoded characters are not "unescaped"

### ISSUE THREAD

**Issue by berbiche** [ErikReider/SwayNotificationCenter#34]
Some applications send notifications containing XML-encoded entities.
These characters are not replaced when showing the notification.

SwayNotificationCenter:
![image](https://user-images.githubusercontent.com/20448408/147011825-3f9e215e-2e62-4981-8181-91fbccdc613c.png)

Mako:
![image](https://user-images.githubusercontent.com/20448408/147012129-c3f01677-3a3b-4e88-a8c4-8ee35a73c475.png)

Dunst:
![image](https://user-images.githubusercontent.com/20448408/147157469-b4f86281-9c8a-4dc9-ac58-6c6226510452.png)

Tested with `notify-send allo "c&#39;est révolutionnaire"`.

**Comment by ErikReider** [comment]
I'll look into this. Encoding and decoding pango and xml with GTK has been a pain

**Comment by berbiche** [comment]
I glanced at Mako's source code and it uses Pango's `pango_parse_markup` directive: https://github.com/emersion/mako/blob/ddc1849804c8703ec749140e3a55febb5250e934/render.c#L154-L165.

It interprets XML-entities (https://docs.gtk.org/Pango/pango_markup.html).
https://valadoc.org/pango/Pango.parse_markup.html

> Pango uses GMarkup to parse this language, which means that XML features such as numeric character entities such as &#169; for © can be used too.
> 
> The root tag of a marked-up document is `<markup>`, but `pango_parse_markup()` allows you to omit this tag, so you will most likely never need to use it. The most general markup tag is `<span>`, then there are some convenience tags.

**Comment by ErikReider** [comment]
Oh cool! I'll check that out tomorrow

**Comment by ErikReider** [comment]
#35 Should fix this
