### ISSUE TITLE
Rounded corners for notification icon

### ISSUE THREAD

**Issue by ErikReider** [ErikReider/SwayNotificationCenter#349]
### Discussed in https://github.com/ErikReider/SwayNotificationCenter/discussions/348

<div type='discussions-op-text'>

<sup>Originally posted by **julius-boettger** December  6, 2023</sup>
Hello,
I just can't figure out how to get rounded corners on the notification icons. It currently looks like this, but I would much prefer it to have rounded corners.
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/85450899/fecd0c41-ab85-4830-a4a1-604efe70af02)
Any help is appreciated!</div>

**Comment by ErikReider** [comment]
@julius-boettger I've been thinking of adding this myself, so "should" be on the chopping block after I've merged the grouped notifications PR :)

**Comment by julius-boettger** [comment]
Sounds good, thank you! I'm looking forward to using it once it's out.
