### ISSUE TITLE
[Feature] Don't display any notification icon instead of fallback

### ISSUE THREAD

**Issue by julius-boettger** [ErikReider/SwayNotificationCenter#350]
**Is your feature request related to a problem? Please describe.**
When an app tries to use an invalid notification icon a fallback is used. I personally experience this with [abraunegg/onedrive](https://github.com/abraunegg/onedrive), which regularly sends me notifications that look like this:

![image](https://github.com/abraunegg/onedrive/assets/85450899/09d20a66-c57c-46ed-abe1-824cd84b5101)

The fallback icon provides no additional information and looks kind of unpleasant, yet I have no way to change it.

**Describe the solution you'd like**
Instad of a fallback icon, I would prefer no icon to be displayed at all. The built-in notification daemon of the [awesome window manager](https://awesomewm.org/) does this, and it looks like this:

![xorg onedrive](https://github.com/ErikReider/SwayNotificationCenter/assets/85450899/6794d8b9-98fb-413d-86a6-05feaacb08e6)

I prefer this solution over the fallback icon that `swaync` currently uses.

**Describe alternatives you've considered**
I have considered that my preferred solution might not be everyone's, so it might make sense to implement a configuration option in `config.json` for this.

**Additional context**
Before noticing that this issue belongs here, I tried raising an [issue](https://github.com/abraunegg/onedrive/issues/2557) over at [abraunegg/onedrive](https://github.com/abraunegg/onedrive) first.

**Comment by ErikReider** [comment]
There's a config option for this...

**Comment by julius-boettger** [comment]
@ErikReider I'm sorry, there is? What is its name? The closest one I could find is `"image-visibility"`, which I have set to `"when-available"` in my `config.json`. But this does not produce the behavior I want, which is why I raised this feature request.

**Comment by julius-boettger** [comment]
Yeah, I think that's it. In the issue over at [abraunegg/onedrive](https://github.com/abraunegg/onedrive) that I mentioned I also suspected that OneDrive is providing an invalid image, which is why `swaync` uses a default fallback icon.

Here is the requested debug output:
```
** (swaync:54453): DEBUG: 20:36:48.402: notiDaemon.vala:171: Notification:
category:		 (null)
image_data:		 false
expire_timeout:		 -1
replaces_id:		 0
desktop_entry:		 (null)
body:		 	Initializing the Synchronization Engine ...
app_icon:		 IGNORED
action_icons:		 false
time:		 	1701977808
hints:		
	sender-pid: int64 54470
applied_id:		 1
image_path:		 (null)
inline-reply:		 (null)
app_name:		 src/notifications/dnotify.d
summary:		 OneDrive
icon_data:		 false
resident:		 false
default_action:		 (null)
actions:		
urgency:		 Low
```

**Comment by ErikReider** [comment]
Pushed a fix. Thanks for the bug report :)

**Comment by julius-boettger** [comment]
Great! Thank you :) That will look so much better. I'm tired of seeing that fallback icon...

**Comment by julius-boettger** [comment]
@ErikReider as of v0.10.1, this issue still exists in the exact form I initially described. It seems like 09c14e4ea968641abfc7f8c0aba5649ef9987b89 did not fix this issue, or at least not for my use case (onedrive). Any ideas?
