### ISSUE TITLE
[Bug] .control-center-list not showing

### ISSUE THREAD

**Issue by AmirDahan** [ErikReider/SwayNotificationCenter#351]
**Describe the bug**
.control-center-list shows up when you first start swaync but .control-center-list-placeholder does not
(As if there is an invisible notification)
But if you receive a notification and close out of it the placeholder shows up but the list doesn't.

Ideally i would like for the placeholder to be shown when there are no notifications
and for the list to be visible at all times (I'm using min-height) to get a dynamically sized notification center.

**To Reproduce**
1. start swaync from a terminal with GTK_DEBU=interactive
2. Toggle the notification center (swaync-client -t)
3. Observe that the placeholder is not visible but list is visible
4. Send notification (notify-send "Test")
5. Close the test notification
6. Observe that the list is now gone and that the placeholder is visible
7. In the GTK inspector, Navigate and hide the placeholder (visible FALSE)
8. Observe the list magically coming back!

**Expected behavior**
Placeholder would be visible when there are no active notifications
List to be visible at all times (As it currently is despite this bug)

**Screenshots**
![ss0](https://github.com/ErikReider/SwayNotificationCenter/assets/72354122/90fed6ea-987f-4cf5-a57a-97f5fb67daf5)
![ss1](https://github.com/ErikReider/SwayNotificationCenter/assets/72354122/d9fe8733-d488-4f2d-9e13-c326f08c1474)
![ss2](https://github.com/ErikReider/SwayNotificationCenter/assets/72354122/01c0a6bf-1500-45ac-a0ef-f80fdaf33155)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version Rolling release

**Additional context**
Red is the list (min-height: 5px)
Green is the placeholder

**Comment by ErikReider** [comment]
Thanks! Fixed :)

**Comment by AmirDahan** [comment]
I'm afraid not, The stack widget cannot be dynamically sized.
