### ISSUE TITLE
[Bug] No icon shown in notifications

### ISSUE THREAD

**Issue by SteelT1** [ErikReider/SwayNotificationCenter#356]
**Describe the bug**
  When showing a notification, the icon in a notification isn't shown, and instead, a blank space of where the icon would normally be shown is there instead.

**To Reproduce**
1. notify-send text -i call-start 

**Expected behavior**
Icon in notification appears correctly

**Please provide logs if you're experiencing notification errors / bugs**
https://gist.github.com/SteelT1/5b0f25a3b2814c69be8b2672aeb5e844

**Screenshots**
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/9903201/f41d5a48-c140-4cd1-b6e4-b343863121d3)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 0.9.0 (git-1fcef5c, branch 'main')

**Additional context**
This only applies to local icons, icons from web notifications appears just fine.

**Comment by MrPenguin07** [comment]
I've also noticed this regression.

I am however impressed with the new notification grouping and styling changes :)

**Comment by MrPenguin07** [comment]
I think this may need to be reopened :/

Built the latest master with the fix;
(after figuring out the new dep on granite, and gtk-layer-shell now requiring +vala on Gentoo which previously did not)
I now see an icon - however it's something of an icon placeholder rather than the specified icon.

Eg. I send notifications to Swaync via a script containing: 
`notify-send -e -i /usr/share/icons/Papirus/16x16/apps/system76-driver.svg 'Balanced power profile set'`

Result
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/127086564/c686ad22-0a5c-4147-9485-aaf4cd1b76c3)

Previously there was no icon; placeholder or otherwise

**Comment by MrPenguin07** [comment]
Another script I have which sends notifs ends up like this;

![image](https://github.com/ErikReider/SwayNotificationCenter/assets/127086564/e3feb559-bcf0-4645-82f0-533264a103b7)

**Comment by ErikReider** [comment]
> I think this may need to be reopened :/
> 
> Built the latest master with the fix;
> (after figuring out the new dep on granite, and gtk-layer-shell now requiring built with +vala on Gentoo which previously did not)
> I now see an icon - however it's something of an icon placeholder rather than the specified icon.
> 
> Eg. I send notifications to Swaync via a script containing: 
> `notify-send -e -i /usr/share/icons/Papirus/16x16/apps/system76-driver.svg 'Balanced power profile set'`
> 
> Result
> ![image](https://github.com/ErikReider/SwayNotificationCenter/assets/127086564/c686ad22-0a5c-4147-9485-aaf4cd1b76c3)
> 
> Previously there was no icon; placeholder or otherwise

The icon has to be in the URI format (starting with file://)

**Comment by MrPenguin07** [comment]
> The icon has to be in the URI format (starting with file://)

My configuration has not changed recently; URI format has certainly never before been required.
Is this change in `notify-send` or how swaync interprets them?

FWIW, I can use the URI in my scripts to see an icon. It is however at a far lower resolution than the original - looks as blocky as minecraft.

**Comment by ErikReider** [comment]
> My configuration has not changed recently; URI format has certainly never before been required.
> Is this change in `notify-send` or how swaync interprets them?

This is a recent swaync change. I read the [notification spec](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html) again and they only support the URI standard. If other daemons like dunst support a regular path, let me know and I'll add it back :)

I want swaync to follow the standards while being as customizable as possible, which is why I changed the behavior.

> FWIW, I can use the URI in my scripts to see an icon. It is however at a far lower resolution than the original - looks as blocky as minecraft.

Can you send a screenshot with the command used and the image used?

**Comment by MrPenguin07** [comment]
> > My configuration has not changed recently; URI format has certainly never before been required.
> > Is this change in `notify-send` or how swaync interprets them?
> 
> This is a recent swaync change. I read the [notification spec](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html) again and they only support the URI standard. If other daemons like dunst support a regular path, let me know and I'll add it back :)
> 
> I want swaync to follow the standards while being as customizable as possible, which is why I changed the behavior.
> 
> > FWIW, I can use the URI in my scripts to see an icon. It is however at a far lower resolution than the original - looks as blocky as minecraft.
> 
> Can you send a screenshot with the command used and the image used?

Funny you mention that, I did just test with dunst and yes icon appears fine without using URI heh.
Here's with dunst;
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/127086564/1bd0ed9f-e7c4-4560-ae20-ec5a03133346)

and with swaync;
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/127086564/7cc06a29-3be8-44de-9a0e-b7a155434b10)

I can assure the .svg being called is of high quality and previous swaync HEADs i've been on have all shown it in high qual.

Regards

**Comment by ErikReider** [comment]
> Funny you mention that, I did just test with dunst and yes icon appears fine without using URI heh.

Ok, good to know! I'll get to it when I have time :)

> and with swaync;

That's because you're providing a 16x16 png...

**Comment by MrPenguin07** [comment]
> > Funny you mention that, I did just test with dunst and yes icon appears fine without using URI heh.
> 
> Ok, good to know! I'll get to it when I have time :)
> 
> > and with swaync;
> 
> That's because you're providing a 16x16 png...

Much appreciated as always!
It's an svg which scales up to 4k flawlessly :)

**Comment by ErikReider** [comment]
> It's an svg which scales up to 4k flawlessly :)

The SVG specifies the height and the width to 16px, which would explain why it's blurry. Setting the scaling filter to FAST would show the pixels, so that wouldn't fix it.

![image](https://github.com/ErikReider/SwayNotificationCenter/assets/35975961/7d32d3b9-de72-4e60-bc86-2e7ee42016ed)

**Comment by MrPenguin07** [comment]
> The SVG specifies the height and the width to 16px, which would explain why it's blurry. Setting the scaling filter to FAST would show the pixels, so that wouldn't fix it.

Well interestingly enough, I went back to HEAD 5a23d5eeb576bf981ad40906453366d14e64736a to compare;
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/127086564/e0f0386c-1874-416d-9fc3-7ac3a3fdc19c)

Back to high quality 16x16 heh so something changed.

In any case this is more of an oddity now, I also have these same svg in the 32x32, 48x48, 64x64 etc folders so i've updated my scripts to use the 48x48 versions and they look great once again.

Cheers i'll update my scripts and enjoy the immense work you've put into grouping and whatnot lately.
Regards

**Comment by ErikReider** [comment]
> > The SVG specifies the height and the width to 16px, which would explain why it's blurry. Setting the scaling filter to FAST would show the pixels, so that wouldn't fix it.
> 
> Well interestingly enough, I went back to HEAD [5a23d5e](https://github.com/ErikReider/SwayNotificationCenter/commit/5a23d5eeb576bf981ad40906453366d14e64736a) to compare; ![image](https://private-user-images.githubusercontent.com/127086564/291901031-e0f0386c-1874-416d-9fc3-7ac3a3fdc19c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzg0MDIsIm5iZiI6MTcwMzA3ODEwMiwicGF0aCI6Ii8xMjcwODY1NjQvMjkxOTAxMDMxLWUwZjAzODZjLTE4NzQtNDE2ZC05ZmMzLTdhYzNhM2ZkYzE5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxMzE1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDNkY2IxMjJlZjQyNjQ5YjIyYmNkZjcwZjRjODgzYTkxN2FkMzFlNzE3YTk2MjVmMDRmYzZjNmZmYTllYmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wIjznSgaccST8lEfkjw7K4MUXtiDza9R-ykxOjO9nqg)
> 
> Back to high quality 16x16 heh so something changed.

Very strange indeed... I'll also look into this. Thanks for bisecting :)

**Comment by ErikReider** [comment]
I'll post another commit to fix the blurryness when I find out what's the root cause

**Comment by ErikReider** [comment]
@MrPenguin07 74ba2f37 fixes the issue

**Comment by MrPenguin07** [comment]
> @MrPenguin07 [74ba2f3](https://github.com/ErikReider/SwayNotificationCenter/commit/74ba2f375d416b947f4258a7ff4af5cf444ac41b) fixes the issue

Nailed it this time :) Cheers
