### ISSUE TITLE
[Bug] gtk-layer-shell not found error while compiling live version.

### ISSUE THREAD

**Issue by mrpingo** [ErikReider/SwayNotificationCenter#358]
**Describe the bug**
Compile error:
error: Package `gtk-layer-shell-0' not found in specified Vala API directories or GObject-Introspection GIR directories

**To Reproduce**
Just compile the live version of SwayNC

**Expected behavior**
No errors while compiling

**Please provide logs if you're experiencing notification errors / bugs**
The important snippet of log code while compiling from sources (LIVE VERSION):

...
Run-time dependency gtk-layer-shell-0 found: YES 0.8.1
...
error: Package `gtk-layer-shell-0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
...

**Complete log is attached as a file.**
[SwayNC-9999-build.log](https://github.com/ErikReider/SwayNotificationCenter/files/13733580/SwayNC-9999-build.log)

**Desktop (please complete the following information):**
 - OS: Gentoo Latest

**Additional context**
This issue happened after a change in code this week. From a day to the next one couldn't compile it.

PS: Many thanks for keep improving this useful tool.

Regards

**Comment by ErikReider** [comment]
I'm not sure how the compilation in Gentoo works but this might help: https://github.com/ErikReider/SwayNotificationCenter/issues/356#issuecomment-1863777438

I bumped some dependency version requirements and added some. The readme specifies all of the dependencies

**Comment by mrpingo** [comment]
Hello!
just recompiled gtk-layer-shell with vala suport and everything just compiled fine! and also the icons is shown pretty neat!
I am going to add this change to my local repo ebuild to make sure this keep recompiling.

Awesome!
