### ISSUE TITLE
try using releases for swaync

### ISSUE THREAD

**Issue by AlfredEVOL** [ErikReider/SwayNotificationCenter#36]
it would be better if swaync would be released as versions as its not fun to make it and restart swaync after every commit...
and make the AUR package use the release and not -git

**Comment by ErikReider** [comment]
Which package manager are you using? For me it prompts me to update my install every time I update the PKGBUILD file.

That's an interesting idea :)

**Comment by AlfredEVOL** [comment]
i am on arch, with paru as the wrapper for pacman....i have had 3 or 4 updates in the last few days for swaync...
If u make releases periodically, and make a new package swaync along with swaync-git, swaync would be the stable one and swaync-git could be used for testing

There is releases option on github...you can just make a new PKGBUILD with just the pkgver to be updated everytime you release a new versiom...

**Comment by nightly-brew** [comment]
yay seems to suffer from the opposite problem, meaning I either reinstall the package manually or I don't get updates at all, probably due to version caching.
+1 for @AlfredEVOL proposal.

**Comment by jirutka** [comment]
At least tagging versions would be really beneficial for linux distributions.

**Comment by nightly-brew** [comment]
Would it be too much to have two versions of the PKGBUILD?

To satisfy everyone, it could be possible to have
- one for devel updates, so the latest commits can be fetched right away, still using the pkgver() function to automatically check for new versions.
- one that doesn't use pkgver() function but which pkgver variable is "sort of" manually updated to point to the latest release tag on every new update.

The first type is the one we have right now, the second one would obviously require setting up a release strategy, which might be the real burden here.

**Comment by AlfredEVOL** [comment]
a bi-weekly release with all the stable commits till that point would work

**Comment by ErikReider** [comment]
78c645d4a0be822d0c9d3e02f9bad29ca7566f2f should fix this. The non git version is called `swaync` on the AUR. There are also releases here on GitHub if anyone's not running arch
