### ISSUE TITLE
Could not acquire notification name. Please close any other notification daemon like mako or dunst

### ISSUE THREAD

**Issue by Motchi0731** [ErikReider/SwayNotificationCenter#363]
I removed the dunst but still im receiving this error.
[bug.txt](https://github.com/ErikReider/SwayNotificationCenter/files/13798101/bug.txt)

**Comment by ErikReider** [comment]
Dunst can be installed, just not be running.

**Comment by vaskark** [comment]
I'm getting the same error, and dunst is not running. Latest git on Ubuntu 26.04.
