### ISSUE TITLE
backlight for amd cpu 

### ISSUE THREAD

**Issue by JaKooLit** [ErikReider/SwayNotificationCenter#364]
**Please read through the README and the Man pages before submitting**
**Please also make sure that there isn't any prior issue describing this bug**

**Describe the bug**
Seems that the backlight is tied to intel_backlight. 

**To Reproduce**
1.) copied schema into same folder on ~/.config/swaync
2.) Edited config.json to schema: "$HOME$/.config/swaync/configSchema.json"
3.) Edited $HOME$/.config/swaync/configSchema.json backlight device to default: amdgpu_bl0 
(since thats the one on my /sys/class/backlight
4.) swaync-client -R
5.) launch swaync on tty. got a warning. Could not find device /sys/class/backlight/intel_backlight/brightness

**Expected behavior**
control of brightness since I dont have intel

**Screenshots**
to follow

**Desktop (please complete the following information):**
 - OS: Gentoo, Arch, Fedora, OpenSuse

**Additional context**

**Comment by JaKooLit** [comment]
![Screenshot_02-Jan_13-11-09_5213](https://github.com/ErikReider/SwayNotificationCenter/assets/85185940/ac32dc6a-5fb1-4a8c-a5af-a92ef600bba8)

**Comment by ErikReider** [comment]
Don't edit the configSchema, copy the default config from /etc/xdg/swaync. The configSchema is only used to get JSON completion with supported editors

**Comment by JaKooLit** [comment]
so in other words its not fully supported..

got it.. thanks

**Comment by ErikReider** [comment]
> so in other words its not fully supported..

What is not supported? Any backlight should be supported

**Comment by JaKooLit** [comment]
> > so in other words its not fully supported..
> 
> What is not supported? Any backlight should be supported

the default config.json from the /etc/xdg/swaync does not have buttons grid, volume, backlight.. etc... thats why I added in the copied config.json from /etc/xdg/swaync all the extras that I wanted.

but when I launch swaync through tty, I have got that message that cannot find intel_backlight, because I dont have intel backlight. That is why I thought about editing that configSchema.json to remove that intel_backlight and change with what backlight I have. which is amdgpu_bl0 but when I relaunch swaync, it is still looking for intel_backlight

**Comment by ErikReider** [comment]
Have you edited the backlight `widget-config`?

```json
"widget-config": {
    "backlight": {
      "subsystem": "backlight",
      "device": "amdgpu_bl0"
    }
}
```

**Comment by JaKooLit** [comment]
> Have you edited the backlight `widget-config`?
> 
> ```json
> "widget-config": {
>     "backlight": {
>       "subsystem": "backlight",
>       "device": "amdgpu_bl0"
>     }
> }
> ```

excellent..

Thanks for pointing that out. It works
