### ISSUE TITLE
[Bug] Inline Replies Don't Show

### ISSUE THREAD

**Issue by chookity-pokk** [ErikReider/SwayNotificationCenter#378]
**Describe the bug**

Looking through the release notes I saw that online replies were introduced in #221. Though when trying to get this behavior with both examples shown in that PR, I get regular notifications without an inline reply text box. 

**To Reproduce**
1. Install swaync via the AUR (swaync not swaync-git).
2. Go to https://tests.peter.sh/notification-generator/ and get a notification or run `notify-send 'Title' 'body' -A inline-reply=Text`

**Expected behavior**
You should get a notification similar to the screenshot in #221.

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Swaync version 0.9.0 (git-bcbca75, branch 'master')

**Comment by ErikReider** [comment]
What compositor are you running?

**Comment by chookity-pokk** [comment]
Sway 1.8.1

**Comment by ErikReider** [comment]
> Sway 1.8.1

Sway 1.8.1 doesn't support the layer shell feature needed. 1.9 has support for it. Until 1.9 is released, the inline reply will only be visible in the control center

**Comment by chookity-pokk** [comment]
Just to clarify, are you saying that the inline display should still be visible in the control center without Sway 1.9 or that it won't be visible until 1.9? 

Because as if you are saying the former, I don't see the online reply in the control center.

**Comment by clinta** [comment]
> Just to clarify, are you saying that the inline display should still be visible in the control center without Sway 1.9 or that it won't be visible until 1.9?
> 
> Because as if you are saying the former, I don't see the online reply in the control center.

I see the same behavior with hyprland.
