### ISSUE TITLE
[Bug] incorrect alignment in the panel with positionY=bottom

### ISSUE THREAD

**Issue by kolalok** [ErikReider/SwayNotificationCenter#391]
With the config option `positionY` set to `bottom`, notifications align to the bottom of the notification panel, as expected.
In previous version (0.9.0) there was a sufficient gap between the last notification and the bottom of the panel.
However in 0.10.0 the last notification is partially positioned past the end of the window.
It is not a critical problem, but it does not look well, when there's usually plenty of space above.

0.9.0:
![obrazek](https://github.com/ErikReider/SwayNotificationCenter/assets/100677843/04930a2e-3076-43ba-9b99-12d266c4a0b0)

0.10.0:
![obrazek](https://github.com/ErikReider/SwayNotificationCenter/assets/100677843/73a0c061-b796-4a52-bb3e-cfb7052e6cea)

It behaves the same with or without Waybar running, and also with `control-center-exclusive-zone` turned off.

1. Use default config files and only change `positionY` to `bottom`
2. Send a notification
3. Open the notification panel
4. See the problem

[swaync.log](https://github.com/ErikReider/SwayNotificationCenter/files/14407887/swaync.log)

OS, versions:
- gentoo linux, Sway 1.9
- swaync 0.10.0

**Comment by kellya** [comment]
I just installed this today, and saw the same thing.  I "fixed" it by adding a `margin-bottom: 50px;` to the style css in `.control-center .control-center-list`.  So it looks like
```
.control-center .control-center-list {
  /* List of notifications */
  background: transparent;
  margin-bottom: 50px;
}
```
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/168120/5b276877-8c8b-413a-9879-6129067209fc)

**Comment by ErikReider** [comment]
> I just installed this today, and saw the same thing. I "fixed" it by adding a `margin-bottom: 50px;` to the style css in `.control-center .control-center-list`. So it looks like
> 
> ```
> .control-center .control-center-list {
>   /* List of notifications */
>   background: transparent;
>   margin-bottom: 50px;
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/168120/309357851-5b276877-8c8b-413a-9879-6129067209fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTc4MTYsIm5iZiI6MTcwOTkxNzUxNiwicGF0aCI6Ii8xNjgxMjAvMzA5MzU3ODUxLTViMjc2ODc3LThjOGItNDEzYS05ODc5LTYxMjkwNjcyMDlmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxNzA1MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjkyOTEzYjc0MTQ3MGVkY2UzMDA5YjFiZGZlOWE4NTA3YThlYTVjNDc4YzI1ZmM3MGRmZjIwNzFjMzYwMDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.noPZfOgnM9yp_DqbAcJJo4IjyXqktsqpj-EC5bJ02Y4)

The pr fixes this without any needed CSS tweaks :)

**Comment by kolalok** [comment]
perfect! thank you
