### ISSUE TITLE
[Bug] slurp output seems captured when running command

### ISSUE THREAD

**Issue by desdic** [ErikReider/SwayNotificationCenter#393]
Hi,

I tried making a screenshot button like 

```json
    "buttons-grid": {
      "actions": [
        {
          "label": "screenshot",
          "command": "/sbin/grim -g \"$(/sbin/slurp)\" - | /sbin/swappy -f -"
        },
```
and without slurp it works but it seems that the output from slurp is captured somehow because the process is running (and hangs due to waiting for the user to choose a region) but its never output. If running it via hyprland it works

**Desktop (please complete the following information):**
 - OS: Arch / Hyprland

**Comment by Abduiwahb** [comment]
You need to use a script for that. And you also need to close the control center after clicking on the screenshot button, which can be done like this.

        {
          "label": "screenshot",
          "command": "sh -c '/path/to/script/screenshot & swaync-client -cp'",
        },

**Comment by desdic** [comment]
> You need to use a script for that. And you also need to close the control center after clicking on the screenshot button. Without it, slurp just hangs. you could try doing something like this.
> 
> ```
>     {
>       "label": "screenshot",
>       "command": "sh -c '/path/to/script/screenshot & swaync-client -cp'",
>     },
> ```

this works perfectly, thanks!
