### ISSUE TITLE
[Bug] Failed to deserialize "image-visibility" error when loading swaync

### ISSUE THREAD

**Issue by d3-X-t3r** [ErikReider/SwayNotificationCenter#396]
**Describe the bug**
When the swaync daemon is loaded, journalctl records the following error: `Failed to deserialize "image-visibility" property of type "SwayNotificationCenterImageVisibility" for an object of type "SwayNotificationCenterConfigModel"`

The full log is as follows:

```
systemd[21531]: Starting Swaync notification daemon...
swaync[27656]: configModel.vala:289: Loading Config: "/home/dexter/.config/swaync/config.json"
swaync[27656]: Failed to deserialize "image-visibility" property of type "SwayNotificationCenterImageVisibility" for an object of type "SwayNotificationCenterConfigModel"
swaync[27656]: functions.vala:86: Loading CSS: "/etc/xdg/swaync/style.css"
swaync[27656]: functions.vala:100: Loading CSS: "/home/dexter/.config/swaync/style.css"
swaync[27656]: factory.vala:44: Loading widget: dnd
swaync[27656]: factory.vala:44: Loading widget: buttons-grid
swaync[27656]: factory.vala:44: Loading widget: mpris
swaync[27656]: factory.vala:44: Loading widget: volume
swaync[27656]: backlightUtil.vala:41: Could not find device /sys/class/backlight/intel_backlight/brightness
swaync[27656]: factory.vala:44: Loading widget: backlight
swaync[27656]: factory.vala:44: Loading widget: title
```

**To Reproduce**
1. systemctl --user stop swaync
2. notify-send -a "MyApplicationName" "This Is The Summary" "hello world"  
3. Check journalctl

**Expected behavior**
There should be no errors.

**Please provide logs if you're experiencing notification errors / bugs**
[swaync_error.log](https://github.com/ErikReider/SwayNotificationCenter/files/14488998/swaync_error.log)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - WM: Wayfire 0.8.0-5
 - swaync: 0.10.0-1
 - wlroots: 0.16
 
**Additional context**
N/A

**Comment by ErikReider** [comment]
Can you provide your config?

**Comment by d3-X-t3r** [comment]
> Can you provide your config?

Apologies for the late reply, here you go: [config.json](https://github.com/ErikReider/SwayNotificationCenter/files/14609871/config.json)

**Comment by ErikReider** [comment]
The `image-visibility` property value that's in your config is misspelled xD

It's `when-available`, not `when available`
