### ISSUE TITLE
[Feature] New release version to fix #388

### ISSUE THREAD

**Issue by StayPirate** [ErikReider/SwayNotificationCenter#397]
Hi @ErikReider, as I reported [here](https://github.com/ErikReider/SwayNotificationCenter/issues/388#issuecomment-1971599417), would be possible to create a new release to easily propagate the fix for #388 on all the downstream distros that are not closely follow the master branch?

**Comment by ErikReider** [comment]
Currently waiting for #370 before a new release :)
