### ISSUE TITLE
[Bug] Script execution leaks pipe FDs

### ISSUE THREAD

**Issue by mbethke** [ErikReider/SwayNotificationCenter#408]
[This bug](https://groups.google.com/g/linux.debian.bugs.dist/c/aGUEBqWW3Vg)  just started turning on my system (Arch Linux, Sway 1.9-1, swaync 0.10.1-1): after about 9 days of uptime, every notification is accompanied by an error message saying 

> Failed to run script: example-script
> Output: Too many open files

Swaync's `/proc/$PID/fd` directory currently shows 1018 open files, 1002 of which are pipes.

My Vala-fu is weak, but my suspicion of `execute_command` in [src/functions.vala](https://github.com/ErikReider/SwayNotificationCenter/blob/be1533ad7fa5e27a156aa996bac7b9fc4fb6026f/src/functions.vala#L351) is still strong ;) It looks like  `std_output` isn't being closed if something goes wrong between spawning the process and setting up the child watch, although I can't think of too many things that could. As notoriously fiddly as this spawning stuff is especially in a portable way, I wouldn't be surprised if it was a GTK/Vala bug either.

[Here's my config in case it helps](https://github.com/ErikReider/SwayNotificationCenter/files/14760299/config.json).

**Comment by ErikReider** [comment]
Are you running the latest version?

**Comment by mbethke** [comment]
Turns out I probably wasn't; meanwhile there's been an update of the Arch package and it's not happening any more.
