### ISSUE TITLE
[Bug] Background not blured

### ISSUE THREAD

**Issue by LeVraiArdox** [ErikReider/SwayNotificationCenter#424]
**Describe the bug**
The background is not blurred in hyprland, making it hard to look at

**Expected behavior**
The background should be blurred and not transparent

**Screenshots**
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/110931544/ddcc1070-a9b9-47de-bd96-8d9ad639c6bd)

**Desktop (please complete the following information):**
 - OS: AxOS (Arch Distribution)
 - WM: Hyprland-git (last version)

**Comment by ErikReider** [comment]
This is not a swaync issue. It's the compositors deal to blur swaync which can be done in hyprland. Closing

**Comment by iDenso** [comment]
A bit late but to answer @LeVraiArdox,
You can change that with a [layerrule](https://wiki.hyprland.org/Configuring/Window-Rules/#layer-rules) in your hyprland config
A combination that works well for me
```
layerrule = blur, swaync-control-center
layerrule = ignorezero, swaync-control-center
```
