### ISSUE TITLE
[Bug] MPRIS module is persistent even when no media is being played

### ISSUE THREAD

**Issue by andrewsebek** [ErikReider/SwayNotificationCenter#425]
Like the title says, I created a Waybar with a MPRIS module, and that caused the MPRIS module in Swaync to be persistent, and the module shows no info. When there's no media, my Waybar shows nothing, but the module appears in Swaync. I have a rice with different Waybar themes, and in two of them I included the MPRIS module. In the other 22, there's no module. If I pick one of those Waybar themes with no MPRIS module, and restart my system, the MPRIS module behaves as expected (only displayed when some media is being played) but once I pick one of the themes showed on screenshot, it becomes persistent, no matter if I switch themes.

**Expected behavior**
When no media is being played in one of the Waybar themes with MPRIS module on it, MPRIS module in Swaync should disappear

**Screenshots**
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/121652305/26c945dd-3786-4f75-991b-5d5a1b544243)

**Desktop:**
 - OS: Arch Linux
 - WM: Hyprland

**Comment by 10f7c7** [comment]
check if playerctl is running in the background, sometimes the MPRIS module for waybar activates it

**Comment by andrewsebek** [comment]
> check if playerctl is running in the background, sometimes the MPRIS module for waybar activates it

Yes, actually it was running. I killed the process and the player widget in Swaync disappeared, but the MPRIS module showed no info when I opened a media player. I had to restart my Waybar to make the module available, and the problem persists. Maybe I need to think more about how to solve this... But yes, it's the MPRIS module causing that.
