### ISSUE TITLE
Option to filter/mask notifications

### ISSUE THREAD

**Issue by diggit** [ErikReider/SwayNotificationCenter#436]
**Is your feature request related to a problem? Please describe.**
There are [applications](https://github.com/Frederick888/git-credential-keepassxc), which produce notifications and I am not interested in those. [Is is not possible to turn notification at the source](https://github.com/Frederick888/git-credential-keepassxc/issues/59).
I used [dunst](https://github.com/dunst-project/dunst) in past and it had a way of [filtering](https://github.com/dunst-project/dunst/blob/master/docs/dunst.5.pod#rules) out of notifications. Similar to what scripting in swaync does, but it was possible to do some action on notification without external script.

**Describe the solution you'd like**
Same way as in scripting matches notification to script, I would like to have an option to alter/mask out the notification.

**Describe alternatives you've considered**
Disabling notification at the source app - [not accepted by author](https://github.com/Frederick888/git-credential-keepassxc/issues/59#issuecomment-1309817748).

**Comment by ErikReider** [comment]
Already a feature :)

```json
  "notification-visibility": {
    "some name":{
      "app-name": "the app name of the application",
      "state": "ignored",
    }
  },
```
