### ISSUE TITLE
[Feature] Use `desktop-entry` if present to display icon

### ISSUE THREAD

**Issue by kuba-gaj** [ErikReider/SwayNotificationCenter#447]
Hi,
I recently switched to `swaync` and noticed I don't see almost any app icons on my system. After some investigation, it looks like `app_icon` is usually empty, but `desktop_entry` is present.

From the [specification](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#hints):
`"desktop-entry"	STRING	This specifies the name of the desktop filename representing the calling program. 
This should be the same as the prefix used for the application's .desktop file. An example would be "rhythmbox" from "rhythmbox.desktop". This can be used by the daemon to retrieve the correct icon for the application, for logging purposes, etc. 
`

Here is an example notification from `Slack`:

```
category:                (null)
image_data:              false
expire_timeout:          -1
replaces_id:             0
desktop_entry:           Slack
body:                   What do you know, it works?
app_icon:
action_icons:            false
time:                   1719756849
hints:
        sender-pid: int64 9071
        urgency: byte 0x01
        desktop-entry: 'Slack'
applied_id:              1
image_path:              (null)
inline-reply:            (null)
app_name:                Slack
summary:                 New message from Slackbot
icon_data:               false
resident:                false
default_action:          Name: View, Id: default
actions:
urgency:                 Normal

```

**Comment by kuba-gaj** [comment]
So after some more investigation I noticed that it is implemented but doesn't always work for me.
With the example above, both `desktop-entry` and ` app_name` are set to `Slack`, but desktop file provided by application is `slack.desktop` (lowercase).

If I copy / symlink `Slack.desktop` to `slack.desktop` the icon shows. But it's not ideal as it causes duplicate entries in launchers. I wonder if you would consider some other fix, maybe:
- case-insensitive check when looking for `desktop` entry
- checking `Name=` value in `.desktop` entry to find correct application
- adding option for users to create mappings for app names and/or desktop entrries

**Comment by ErikReider** [comment]
We already look for the desktop entry, but swaync can't do anything about misbehaving applications that don't provide the correct “.desktop” filename. In the past Discord provided "Discord" as the desktop-entry, but they've fixed it and now provide "com.discordapp.Discord".

I don't really think that there's anything that can be done except for fixing the root issue at the application level…

**Comment by ErikReider** [comment]
d5cac981 adds lower-case support
