### ISSUE TITLE
[Bug] mpris showing 2 times 

### ISSUE THREAD

**Issue by sachinchaudhary1808** [ErikReider/SwayNotificationCenter#454]
so i see two mpris windows idk why

**Comment by sachinchaudhary1808** [comment]
https://github.com/user-attachments/assets/178df788-13e2-4538-b3d7-0af2e0f0cbc2

**Comment by ErikReider** [comment]
Please follow the issue template. Makes it easier for people to follow and reproduce...

**Comment by sachinchaudhary1808** [comment]
> Please follow the issue template. Makes it easier for people to follow and reproduce...

https://github.com/ErikReider/SwayNotificationCenter/issues/456

**Comment by ErikReider** [comment]
Are you running playerctld in the background?

**Comment by sachinchaudhary1808** [comment]
> Are you running playerctld in the background?

i use playerctl to control my media keys nothing more

**Comment by sachinchaudhary1808** [comment]
> Are you running playerctld in the background?

yeah it's already running

**Comment by ErikReider** [comment]
> yeah it's already running

There's the issue. If you're running the latest -git version, you'd be able to blacklist playerctrld :)

**Comment by sachinchaudhary1808** [comment]
> > yeah it's already running
> 
> There's the issue. If you're running the latest -git version, you'd be able to blacklist playerctrld :)

and how do i do that ? doc ?

**Comment by ErikReider** [comment]
https://github.com/ErikReider/SwayNotificationCenter/blob/8ea8569820209cd1297482ec81f1fffe85ab695a/man/swaync.5.scd?plain=1#L605-L609

**Comment by sachinchaudhary1808** [comment]
> https://github.com/ErikReider/SwayNotificationCenter/blob/8ea8569820209cd1297482ec81f1fffe85ab695a/man/swaync.5.scd?plain=1#L605-L609

thanks

**Comment by sachinchaudhary1808** [comment]
> https://github.com/ErikReider/SwayNotificationCenter/blob/8ea8569820209cd1297482ec81f1fffe85ab695a/man/swaync.5.scd?plain=1#L605-L609

after doing this there is no mpris window now
