### ISSUE TITLE
Enable dbus activation for swaync

### ISSUE THREAD

**Issue by nightly-brew** [ErikReider/SwayNotificationCenter#46]
Hi, I suspect swaync does not register itself as dbus-activable and I think it would be good if it was the case instead.
This should help avoid missing notifications in case no service is started: if dbus gets a "message" for org.freedesktop.Notifications it should be able to start swaync automatically.

This could also explain why in #32 mako was running on top of swaync, it must have been started by dbus (even though swaync should have been bound to org.freedesktop.Notifications so it shouldn't have happened, but my knowledge on the inner workings of dbus is little to zero so I may be wrong).

Do you think it could be a useful change?

**Comment by ErikReider** [comment]
It looks like this is related to #47. I'm closing this to continue it there
