### ISSUE TITLE
Systemd unit file

### ISSUE THREAD

**Issue by nightly-brew** [ErikReider/SwayNotificationCenter#47]
Would it be possible to have swaync shipped by default with a systemd unit file?
I wrote a simple one based on the file that comes with mako, if it may help.

```ini
[Unit]
Description=Swaync notification daemon
Documentation=https://github.com/ErikReider/SwayNotificationCenter
PartOf=graphical-session.target
After=graphical-session.target
Requisite=graphical-session.target
# ConditionEnvironment requires systemd v247 to work correctly
ConditionEnvironment=WAYLAND_DISPLAY

[Service]
Type=dbus
BusName=org.freedesktop.Notifications
ExecStart=/usr/bin/swaync
ExecReload=/usr/bin/swaync-client --reload-config --reload-css
Restart=on-failure

[Install]
WantedBy=graphical-session.target
```

**Comment by ErikReider** [comment]
To start the daemon automatically when receiving a notification, we'll need the `.service` file that you provided above and a small service file that'll need to be copied into `/usr/share/dbus-1/services/`

**Comment by nightly-brew** [comment]
Let me search the one mako uses, if it could be of help.

**Comment by ErikReider** [comment]
Here it is https://github.com/emersion/mako/blob/ddc1849804c8703ec749140e3a55febb5250e934/fr.emersion.mako.service.in

**Comment by nightly-brew** [comment]
Alright, let me finish my lunch and I'll take a look at it, and see if d-fet reports swaync as activable after that.

**Comment by nightly-brew** [comment]
Ok, got it working!

Quick note, the systemd service is called swaync.service.

The dbus service file instead is "/usr/share/dbus-1/org.erikreider.swaync.service", with the following content:
```ini
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/bin/swaync
SystemdService=swaync.service
```

With this, dbus happily starts the service when a notification pops up!

**Comment by ErikReider** [comment]
Cool! Now it just needs some meson work and we'll be done :)

**Comment by nightly-brew** [comment]
First time using meson, but I think I almost got it right.
https://github.com/nightly-brew/SwayNotificationCenter/commit/8e8cf9384beae0b42e9a51317c2358e4db668b2a

Though, I would definitely be happy to hear other's opinion on always including the SystemdService key in the dbus activation file.

[The specification](https://dbus.freedesktop.org/doc/dbus-specification.html) says dbus should try invoking the systemd service only if the dbus instance itself was started with "--systemd-activation", falling back to Exec when that parameter is not used.
Would you leave it be or would you prefer meson to generate a different file?

I also couldn't decide where to put said files in the project tree, so let me know if services is good or not.

**Comment by nightly-brew** [comment]
I was also thinking, should the systemd service enabled on install or should it be left to the user to decide?
In the latter case, we could provide a preset file.

**Comment by ErikReider** [comment]
Could you create a pull request so that we can continue the conversation there?

**Comment by nightly-brew** [comment]
Sure!

**Comment by nightly-brew** [comment]
Closing since the pull request was accepted.
