### ISSUE TITLE
[Bug] CSS file can't be moved

### ISSUE THREAD

**Issue by anmvc** [ErikReider/SwayNotificationCenter#484]
**Please read through the README and the Man pages before submitting**
**Please also make sure that there isn't any prior issue describing this bug**

**Describe the bug**
SwayNC CSS file can not be moved, while the README says otherwise.

**To Reproduce**
1. Run the command "sudo mv /etc/xdg/swaync ~/.config/swaync/
2.  Run "swaync"
3. See Error

**Expected behavior**

**Please provide logs if you're experiencing notification errors / bugs**
Attach Gists for swaync logs by running `G_MESSAGES_DEBUG=all swaync` and (if applicable) application logs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: idk

**Additional context**

**Comment by anmvc** [comment]
true >> false on line 98 of functions.vala fixes it

**Comment by ErikReider** [comment]
What? It literally says "copy". Just copy it instead and your issues will be fixed
