### ISSUE TITLE
[Feature] Ability to toggle the full-screen coverage of the `swaync-control-center` layer (#21)

### ISSUE THREAD

**Issue by iamhrigved** [ErikReider/SwayNotificationCenter#486]
### Problem

I have set `layerrule = blur, swaync-control-center` which should blur the full layer of the control center when it is visible. Now, since the layer covers the full screen, everything on my screen blurs, which I clearly do not want.

**Note:** See #21

### Proposed solution

Probably an option like this in the config would be fine.
```json
{
  "properties": {
    "control-center-close-on-click": {
      "type": "boolean",
      "description": "Wether or not to close the control center when clicking outside it",
      "default": true
    }
  }
}
```

### Additional context

**Image Demo:**
![image](https://github.com/user-attachments/assets/75995322-64e3-4907-9984-a70824183906)

**Output of `hyprctl layers`:**
```
Monitor VGA-1:
	Layer level 0 (background):
		Layer 62cfe7f9a320: xywh: 0 0 1920 1080, namespace: swww-daemon
	Layer level 1 (bottom):
		Layer 62cfe7f836b0: xywh: 0 0 1920 37, namespace: waybar
	Layer level 2 (top):
	Layer level 3 (overlay):
		Layer 62cfe8005500: xywh: 0 37 1920 1043, namespace: swaync-control-center
```

**Comment by ErikReider** [comment]
Not related to swaync. Hyprland has a ignore transparent feature for the blur which fixes this. I don't use it myself so no clue what it's called

**Comment by iamhrigved** [comment]
Thanks! There is a `ignorezero` rule.

```
layerrule = ignorezero, swaync-control-center
```
