### ISSUE TITLE
[Bug] telegram shows notifications in dnd

### ISSUE THREAD

**Issue by forest-cat** [ErikReider/SwayNotificationCenter#489]
**Describe the bug**
While switched on DND some applications like telegram can still send notifications

**To Reproduce**
1. Install Telegram Desktop (Flatpak) and SwayNC
2. Turn on DND in the Control-Center
3. Receive a Notification, it will still be displayed, ignoring dnd

**Expected behavior**
No notification appears, only when opening the control center, then the notification should be visible there

**Please provide logs if you're experiencing notification errors / bugs**
Attach Gists for swaync logs by running `G_MESSAGES_DEBUG=all swaync` and (if applicable) application logs.
Ive put the entire swaync log up here: https://pastebin.com/pMEiuCxZ

**Desktop (please complete the following information):**
 - OS: `Linux 6.6.58, NixOS, 24.05 (Uakari), 24.05.20241030.080166c`
 - SwayNC Version: 0.10.1

**Additional context**
Telegram seems to do weird stuff with notifications, their timeout is somehow not working and also other notification deamons like dunst had problems with them

**Comment by forest-cat** [comment]
> The logs are needed. They'll tell me what priority the notifications request, critical ignoring DND. Not using Nix so I sadly can't help with that :/

Alright, i understand. Got it working with nix and have now provided the link in the issue above. As you suggested its on critical level, is there an option to turn that behavior of?

**Comment by ErikReider** [comment]
> Only thing i have found now is the option to override message priority. Would that work without any other nasty consequences

That would be the one. Shouldn't cause any issues unless you're expecting very urgent notifications from Telegram I guess?

**Comment by forest-cat** [comment]
> > Only thing i have found now is the option to override message priority. Would that work without any other nasty consequences
> 
> That would be the one. Shouldn't cause any issues unless you're expecting very urgent notifications from Telegram I guess?

im having issues setting that option, in my config is:
```
{
  "control-center-layer": "top",
  "control-center-margin-bottom": 20,
  "control-center-margin-left": 0,
  "control-center-margin-right": 10,
  "control-center-margin-top": 20,
  "layer": "overlay",
  "layer-shell": true,
  "notification-2fa-action": true,
  "notification-body-image-height": 100,
  "notification-body-image-width": 200,
  "notification-icon-size": 64,
  "notification-visibility": {
    "patternProperties": {
      "properties": {
        "override-urgency": "normal"
      }
    }
  },
  "positionX": "right",
  "positionY": "top",
  "script-fail-notify": true,
  "widgets": [
    "mpris",
    "title",
    "dnd",
    "notifications"
  ]
}
```

**Comment by ErikReider** [comment]
I'm not currently at my PC but here's an example: https://github.com/ErikReider/SwayNotificationCenter/blob/main/man/swaync.5.scd#L156-L218

You only need one of the fields to identify the notification, so appid for all telegram notifications :)

**Comment by forest-cat** [comment]
yt

> I'm not currently at my PC but here's an example: https://github.com/ErikReider/SwayNotificationCenter/blob/main/man/swaync.5.scd#L156-L218
> 
> You only need one of the fields to identify the notification, so appid for all telegram notifications :)

Sadly i still dont understand how to set those options, could you elaborate further?

**Comment by ErikReider** [comment]
> > I'm not currently at my PC but here's an example: [`main`/man/swaync.5.scd#L156-L218](https://github.com/ErikReider/SwayNotificationCenter/blob/main/man/swaync.5.scd#L156-L218)
> > You only need one of the fields to identify the notification, so appid for all telegram notifications :)
> 
> Sadly i still dont understand how to use/set those options, could you elaborate further?

```json
  "notification-visibility": {
    "telegram-example":{
      "desktop-entry": "org.telegram.desktop",
      "override-urgency": "normal"
    }
  },
```

**Comment by forest-cat** [comment]
yt

> > > I'm not currently at my PC but here's an example: [`main`/man/swaync.5.scd#L156-L218](https://github.com/ErikReider/SwayNotificationCenter/blob/main/man/swaync.5.scd#L156-L218)
> > > You only need one of the fields to identify the notification, so appid for all telegram notifications :)
> > 
> > 
> > Sadly i still dont understand how to use/set those options, could you elaborate further?
> 
> ```json
>   "notification-visibility": {
>     "telegram-example":{
>       "desktop-entry": "org.telegram.desktop",
>       "override-urgency": "normal"
>     }
>   },
> ```

Thanks, now it works. Sorry for the inconvenience. This Project is really cool :+1:
