### ISSUE TITLE
Add close and open functions to swaync-client

### ISSUE THREAD

**Issue by nightly-brew** [ErikReider/SwayNotificationCenter#49]
swaync-client --toggle-panel is great for toggling the center with a simple keybind, but from a scripting point of view it is not possible to force the control center in one of the two statuses directly though the client.

I'm envisioning something like
  swaync-client --open-panel
  swaync-client --close-panel

Unless the program itself doesn't have a feedback on the status of the panel, which I don't think is the case, this sounds relatively easy to implement.

I can try my hand at it tomorrow if you like the idea.

**Comment by ErikReider** [comment]
98c5fb7e09fdae295c150798334cf7684138fe8f adds --open-panel / -op and --close-panel / -cp

**Comment by nightly-brew** [comment]
Thanks, works great!
