### ISSUE TITLE
[Bug]Where are the notifications?

### ISSUE THREAD

**Issue by hornetster** [ErikReider/SwayNotificationCenter#492]
**Please read through the README and the Man pages before submitting**
**Please also make sure that there isn't any prior issue describing this bug**

**Describe the bug**
Can't get any notifications at all.
When system starts, get very brief notification flash up, but then can't find.
I never installed this?!

**To Reproduce**
No notifications??

**Expected behavior**
Notifications available

**Please provide logs if you're experiencing notification errors / bugs**
Attach Gists for swaync logs by running `G_MESSAGES_DEBUG=all swaync` and (if applicable) application logs.

**Screenshots**
![Notifications1](https://github.com/user-attachments/assets/de94d9d4-3f54-4567-9139-3661313da1d5)

**Desktop (please complete the following information):**
Tumbleweed 20241210
Plasma 6.2.4 Wayland

**Additional context**
Not sure how it got installed??
Can find no reference anywhere to this notifications app -  nothing in the software installed, cant search from the start menu...??

**Comment by ErikReider** [comment]
What?? Having swaync installed and working is not a bug. You must've accidentally installed it. Try removing it through your package manager

**Comment by hornetster** [comment]
OK, sorry, had done a search and it had not come up - did a deeper search, and showing...
But - I had never installed it, (never heard of it!) must have been installed by a 3rd party app...
Will uninstall.

**Comment by ErikReider** [comment]
> OK, sorry, had done a search and it had not come up - did a deeper search, and showing...
> 
> But - I had never installed it, (never heard of it!) must have been installed by a 3rd party app...
> 
> Will uninstall.

No worries! Didn't know that swaync could replace Plasmas notifications daemon, so good find! :)

**Comment by hornetster** [comment]
Glad I acheived something, then! :-)
