### ISSUE TITLE
Clear all notifications doesn't trigger default nor close actions for notifications

### ISSUE THREAD

**Issue by nightly-brew** [ErikReider/SwayNotificationCenter#52]
I was playing with notify-send.py, creating notifications with buttons, for the sake of testing orca.

notify-send.py is different from the classic notify-send, as it waits for the notification to either expire, be closed or be acted upon (if it has action buttons, of course), otherwise the script remains waiting for a status change from the notification.

Well, if I click the notification manually or with keyboard it correctly triggers the default action. If I close it, it registers as so.
Even button actions seem to work as intended.

The clear all button in the control center though, it doesn't seem to send a close action to the programs (nor a default, which one is better suited is up to discussion as far as I kow), so things like bluetooth-manager or notify-send.py wait idly for something to happen, but on the swaync side the notification isn't there anymore.

**Comment by ErikReider** [comment]
Could you comment a notify-send.py command that waits for activation?

**Comment by nightly-brew** [comment]
sure!

```sh
notify-send.py "this notification is waiting for you" --action "action_button_1":"for me?" "action_button_2":"no way!"
```

**Comment by nightly-brew** [comment]
Works now, thank you. You're fast!

**Comment by ErikReider** [comment]
Thanks! Accidentally forced pushed over your previous changes a few mins ago but they're back now 😳
