### ISSUE TITLE
Compatibility with out of spec rules?

### ISSUE THREAD

**Issue by ErikReider** [ErikReider/SwayNotificationCenter#56]
[NotifyOSD](https://wiki.ubuntu.com/NotifyOSD)

- [x] `x-canonical-private-synchronous` to replace notification 756229c
- [x] Slider values with hint: `int:value:NUMBER` 4283ab9

**Comment by nightly-brew** [comment]
I would like to contribute.
What would you start with?

**Comment by ErikReider** [comment]
First I think that we should find a more up-to-date source

**Comment by nightly-brew** [comment]
I couldn't find anything newer, not even by browsing through other notification daemon's issues / feature requests.
That page seems to be the latest spec available for notifyOSD.

There is a mention of kdenotification specs, but it seems long forgotten in favour of the xdg standard.

The first missing feature I coud notice is the lack of a progress bar when passing an integer value hint. That would enable swaync to display OSD-like confirmation notifications.

**Comment by nightly-brew** [comment]
Going to work on this after sound support is finished.
Ideally, what style should I use for the osd-like notifications?

I could put a locked slider in the body, or somehow make the body itseld show the range I think. Other ideas?

**Comment by ErikReider** [comment]
There's a GTK box in the body if I remember correctly. That would be the perfect place for a slider

**Comment by nightly-brew** [comment]
Should text be hidden if a text-body is passed as well?
Maybe it could be shown together with the slider.

**Comment by ErikReider** [comment]
> Should text be hidden if a text-body is passed as well? Maybe it could be shown together with the slider.

That makes sense. Is I wonder if there's any way of testing this... I thought that Dolphin displayed a progress notification when compressing files but that may have been patched out since Linus found it annoying

**Comment by nightly-brew** [comment]
notify-send and others should provide flexible enough to work, but if you can find an example of program that has this behaviour, it should indeed provide a better test

**Comment by ErikReider** [comment]
So apparently kdenlive should send notifications with a image preview. I'm not sure if it works here or not

**Comment by nightly-brew** [comment]
Like a whole-body image? I think not

**Comment by ErikReider** [comment]
It works with a <img/> tag in the body:

`notify-send "hello'world" '<img src="~/Pictures/Linus2.png"/>'`
![image](https://user-images.githubusercontent.com/35975961/153011462-8f4ef78b-e136-4a0c-b098-5df3c6a249c4.png)

I'm not sure if Kdenlive sends it as a hint or attaches it into the body though...

Don't mind the wacky waybar icons, just updated font-awesome 6 which broke my config...

**Comment by nightly-brew** [comment]
I was more distracted from that handsome chungus boi you got there!
Anyway I should get some wotk done later today, I can check kdenlive codebase for that
