### ISSUE TITLE
Add way to clear all notifications

### ISSUE THREAD

**Issue by cauebs** [ErikReider/SwayNotificationCenter#6]
Such as a button in the panel.

**Comment by ErikReider** [comment]
I'll add a Client command and a keyboard shortcut right away. Where would you want it? In the Notification panel?

**Comment by cauebs** [comment]
It's not a matter of where I want it, it's what we think is best! I really like the work you're doing and want to help with suggestions.

For me personally, the keyboard shortcut does the job. But it might be clearer to some people to have a button, maybe in the top right of the panel.

**Comment by ErikReider** [comment]
That sounds like a great idea! I just remembered that I need a button for do not disturb too so this is perfect

**Comment by ErikReider** [comment]
I've added a button and a class to style it with CSS. I hope this is was what you were expecting 😄
