### ISSUE TITLE
AUR package does not install

### ISSUE THREAD

**Issue by nwg-piotr** [ErikReider/SwayNotificationCenter#60]
I tried to install the AUR package, and got into [trouble](https://gist.github.com/nwg-piotr/f0b9911198fd122866434ff650ab48bb).

**Comment by ErikReider** [comment]
Why is it trying to build  `vala-dbus-binding-tool-git` instead of the packaged one?

**Comment by nwg-piotr** [comment]
Dunno. Ask the packager. ;)

**Comment by ErikReider** [comment]
Hmmm. I don't remember that the package needed that package but I may be wrong. I'll give it a better look tomorrow :)

**Comment by nwg-piotr** [comment]
Thumbs up.

**Comment by ErikReider** [comment]
@nwg-piotr I removed `vala-dbus-binding-tool-git`and everything should work now :)

**Comment by nwg-piotr** [comment]
Installed successfully. Need to play with it to learn if/how I can add it to the shell. Thanks for resolving the issue.
