### ISSUE TITLE
iOS / Cosmic styled notification stacks

### ISSUE THREAD

**Issue by ErikReider** [ErikReider/SwayNotificationCenter#61]
[Cosmic](https://news.itsfoss.com/system76-cosmic-panel/)
![image](https://user-images.githubusercontent.com/35975961/150807140-cf407ab8-c311-46c9-bc34-46bac0e49708.png)

**Comment by nightly-brew** [comment]
I really like it!
Does it allow the user to expand the grouped notifications and interact with each one singularly?

**Comment by ErikReider** [comment]
> I really like it!
> Does it allow the user to expand the grouped notifications and interact with each one singularly?

Yes sir! Clicking on it expands all of the notifications

**Comment by nightly-brew** [comment]
I wonder now: if the notification on top has buttons, are those shown or are they hidden until the group is expanded?

**Comment by ErikReider** [comment]
That screenshot was from a System76 figma document if I'm not mistaken. My guess would be that they are shown after all notifications are expanded

**Comment by phwelo** [comment]
this would be a serious usability improvement 💯

**Comment by ldelossa** [comment]
this is bad ass :+1:

**Comment by ErikReider** [comment]
I have a work in progress locally on my machine with some pretty nice animations :)

I'll post a PR when I've gotten the actual notification logic in place which should be the "easy" part

**Comment by ErikReider** [comment]
https://github.com/ErikReider/SwayNotificationCenter/assets/35975961/c228b177-fb26-4a92-8ace-9b2d14c635c5

Here's a preview ;)
