### ISSUE TITLE
Consume keyboard events

### ISSUE THREAD

**Issue by nwg-piotr** [ErikReider/SwayNotificationCenter#63]
If you want my advice: keyboard support should "consume" events (return true), in order not to trigger them on other windows. E.g. if I open Azote, which closes on `Esc`, then the notification center, and then press Escape, both windows will be closed. Same applies to the CapsLock key, I suppose, though I'm not sure if it's gonna work. I'd expect it to just close the notification panel, w/o switching the CapsLock state.

**Comment by ErikReider** [comment]
Another example would be Firefox while watching a full screen video on YouTube

**Comment by ErikReider** [comment]
https://github.com/ErikReider/SwayNotificationCenter/blob/64cbae2465e171a13ffadf831e6abd8e0101d50d/src/controlCenter/controlCenter.vala#L33-L42
This should work though... :/

**Comment by nwg-piotr** [comment]
The CapsLock key seem unnecessary/unintuitive to me by the way. :)

**Comment by ErikReider** [comment]
> The CapsLock key seem unnecessary/unintuitive to me by the way. :)

It's for the Vim people ;)
I'll hopefully be able to add a way to add custom keyboard shortcuts in the future

**Comment by nwg-piotr** [comment]
I only know how to exit vim. :D

**Comment by ErikReider** [comment]
Doesn't seem to affect `key_release_event` for some reason

**Comment by nwg-piotr** [comment]
Haha! The `KEY_PRESS` event is broken, I should have noticed and told you. I've already fixed several issues related to it by just using the key release event.

**Comment by ErikReider** [comment]
Smh... I wonder if this is a Layershell issue or a GTK issue though...

Thanks for the help! :)

**Comment by nwg-piotr** [comment]
You're welcome. I've just fixed a bug in `nwg-panel` executor module while testing an executor for `swaync`. A mutual benefit.
