### ISSUE TITLE
nwg-shell integration

### ISSUE THREAD

**Issue by nwg-piotr** [ErikReider/SwayNotificationCenter#66]
Not an issue, and I hope you'll like it:

https://youtu.be/TppgCqHHsE0

**Comment by ErikReider** [comment]
Works like a charm!

**Comment by nwg-piotr** [comment]
It's a half of the job, only makes use of `swanc-client`. I still need to add support for `swaync`, with configs and css sheets customized to my predefined desktop styles.

BTW: If you could add the `-v` flag to print the swaync version one day, I'd show it to the user in `nwg-panel-config`.

**Comment by ErikReider** [comment]
Funny that you should mention the version arg because I was up last night implementing it :)

**Comment by nwg-piotr** [comment]
Excellent!

**Comment by ErikReider** [comment]
https://github.com/ErikReider/SwayNotificationCenter/blob/main/src/ccDaemon/ccDaemon.vala#L42-L58

I added a DBus method to change config values. Could be useful :)

**Comment by ErikReider** [comment]
@nwg-piotr btw, will you be checking the version in nwg-panel? In that case the formatting between the git and the stable versions should be the same

**Comment by nwg-piotr** [comment]
It doesn't really matter. I display info on optional packages in the panel config to let users know they should install them. If installed, the field is mostly to credit the author. 

Of it comes to the ArchLabs implementation of the shell, it will be using a binary package, made from the regular AUR version. AL installer does not support AUR.

**Comment by nwg-piotr** [comment]
ArchLabs sway session is about to use your project. In testing repos now.
