### ISSUE TITLE
Add simpler way to dismiss a notification

### ISSUE THREAD

**Issue by cauebs** [ErikReider/SwayNotificationCenter#7]
Such as a right click, or by dragging to either side.

**Comment by ErikReider** [comment]
I just pushed a commit that added keyboard shortcuts to the notification panel. Are you referring to that panel or the actual popup notifications?

**Comment by cauebs** [comment]
Well, then you're awesome. I meant inside the panel, yes. Amazing timing.

**Comment by ErikReider** [comment]
Should be up now
