### ISSUE TITLE
Investigate support for xdg activation token

### ISSUE THREAD

**Issue by nightly-brew** [ErikReider/SwayNotificationCenter#71]
Was browsing freedesktop gitlab instance and I read about [xdg activation protocol](https://wayland.app/protocols/xdg-activation-v1).
On wayland.app it says it's still staging as a protocol, but in the future this should allow clicking on a notification and automatically focusing the sender's surface on wayland, with specific protections about focus stealing.
(Of course, the compositor needs to support that).

I'm almost sure close to no applications provide said token, nor it's currently standardised, still it would be really good to have.

**Comment by ErikReider** [comment]
I've read that swaync needs to get a token and send it before an action is invoked? I'm not really sure if that's correct or not though

**Comment by nightly-brew** [comment]
Something like that, yes.
To be honest I haven't read it entirely, as I'm working on the sound feature (was searching any issues about phone categories).

I think the sender program first requests an activation token from the compositor, then sends the token along with the notification (one token per notification maybe?).
Next, when the notification has been activated, the token is passed (probably from the noti daemon) to the compositor, and this decides if the token is still valid or not and acts consequently.

I'm really unsure though, don't take my words for granted.

**Comment by slikie** [comment]
with xdg-activation-v1 landed in sway, hope this can be put back on the table
