### ISSUE TITLE
Fix vala namespace typo

### ISSUE THREAD

**Issue by nightly-brew** [ErikReider/SwayNotificationCenter#72]
The namespace around the program is "SwayNotificatonCenter", it lacks an 'i'.

(Just a reminder for myself to fix it)

**Comment by ErikReider** [comment]
Good catch! It seems like I need new contacts...

**Comment by nightly-brew** [comment]
I need the too, tbh!
I couldn't find the reason a class from a new file wasn't visible, until I looked up...

**Comment by nightly-brew** [comment]
I opened a new MR, see #78
