### ISSUE TITLE
[enh] add a way to suppress notifications from a particular application.

### ISSUE THREAD

**Issue by james-lawrence** [ErikReider/SwayNotificationCenter#73]
some notifications are obnoxious. =)

**Comment by nightly-brew** [comment]
Good point.
It should be relatively easy to implement, especially after #58 if I manage to make lists, arrays and such serializable.

We could provide a little bit of granular control, like 
- ENABLED
- MUTED
- IGNORED

What do you think @ErikReider ?

**Comment by ErikReider** [comment]
We should be able to mute notifications from different desktop applications :)

**Comment by james-lawrence** [comment]
@ErikReider I've been waffling on asking this but an api to iterate (along with suppressing) over the messages would be nice too. feeling like a choosy begger atm. ;)

personally I feel like we don't have a notification daemon that is actually the daemon and not a daemon + UI.

**Comment by nightly-brew** [comment]
I was wondering about that today.
On android, companion apps can ask the permission manager to let it see and manage every notification, so they can send it to smartwatches for example.

It does raise a couple of corcerns or two, especially authorization, since a malicious program could use that to gather all sorts of data, even control bluetooth pairing since bluez-manager does it through notifications.

**Comment by james-lawrence** [comment]
the iteration is off topic thou I was mainly asking to see if there is any interest ;) I can open an actual issue if there is.

**Comment by nightly-brew** [comment]
Well, I think the worst outcome of you opening a new feature request is it gets denied.
Erik seems to be a lot welcoming of new features which provide a real benefit, at least that's my opinion.

I'm just a guy really interested in the project.

**Comment by ErikReider** [comment]
> Good point. It should be relatively easy to implement, especially after #58 if I manage to make lists, arrays and such serializable.
> 
> We could provide a little bit of granular control, like
> 
>     * ENABLED
> 
>     * MUTED
> 
>     * IGNORED
> 
> 
> What do you think @ErikReider ?

Just realized that I didn't answer your question... That PR should make it easier to implement this. We could also set the notification type for each category

**Comment by nightly-brew** [comment]
> > Good point. It should be relatively easy to implement, especially after #58 if I manage to make lists, arrays and such serializable.
> > We could provide a little bit of granular control, like
> > ```
> > * ENABLED
> > 
> > * MUTED
> > 
> > * IGNORED
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What do you think @ErikReider ?
> 
> Just realized that I didn't answer your question... That PR should make it easier to implement this. We could also set the notification type for each category

Sure! So far we're down to 3 fields for each cat.

**Comment by ErikReider** [comment]
Hmm... I'm considering making the config option similar to the `script` option. Any better ideas?
