### ISSUE TITLE
[idea] message iteration

### ISSUE THREAD

**Issue by james-lawrence** [ErikReider/SwayNotificationCenter#74]
one thing I was looking for originally with a notification daemon was one with a fully functional api so different UIs could be implemented without having to reimplement all the basic notification daemon work. I couldn't find any. I'm primarily tossing this out there as an idea.

@nightly-brew rightly pointed out some access control would be needed. I have a few ideas in this area. if there is interest in this here I'd happy spit ball some ideas.

**Comment by ErikReider** [comment]
Could you explain in more detail? An example of what you're trying to achieve would also help me understand :)

**Comment by james-lawrence** [comment]
yeah, basically wanted to build an entire custom UI for display the notifications without having to build the entire daemon myself. its entirely a pipedream atm and not in any rush. =) but have yet to find anyone that has decoupled them.

**Comment by ErikReider** [comment]
The UI kinda needs to be tightly integrated with the daemon :/
