### ISSUE TITLE
Blurry images (inefficient resize algorithm?)

### ISSUE THREAD

**Issue by maximbaz** [ErikReider/SwayNotificationCenter#90]
Hello,

Although I'm on HiDPI screen, I don't reproduce #29 so far, and you will see that the text is sharp, but the image is quite blurry.

Take this image for example:

https://assets.petco.com/petco/image/upload/f_auto,q_auto/rabbit-care-sheet

Use it like so: `notify-send -i $PWD/rabbit-care-sheet hello world`

With `swaync`:

![swappy-20220220_221243](https://user-images.githubusercontent.com/1177900/154864612-e4c0e5de-14bb-4c80-ba5b-718771ab29fa.png)

With `mako`:

![swappy-20220220_221300](https://user-images.githubusercontent.com/1177900/154864614-9e70ca76-7a50-45eb-a997-ef5b5431942c.png)

Impressive project, by the way! 🚀

**Comment by ErikReider** [comment]
Hmm. Strange... Can't seem to reproduce it on my end with my 1440p monitor. What resolution are you running?

**Comment by maximbaz** [comment]
```
$ swaymsg -t get_outputs
  Current mode: 3840x2400 @ 59.994 Hz
  Scale factor: 2.000000
...
```

**Comment by maximbaz** [comment]
Do make sure to try with the image above, and maybe also compare with `mako` if you can, I saw a screenshot of `swaync` from someone who is on `1920x1080` with scale `1` and it also seemed blurry to me.. Maybe the issue is only showing up for certain images, or certain aspect ratios for example. I initially noticed it in a chat application, that shows user avatars.

**Comment by ErikReider** [comment]
Is the image in a .webp format on your end? Doesn't seem to work with Gdk Pixmap so I converted it to a jpg in GIMP

**Comment by ErikReider** [comment]
I think I actually made it look better than mako but I'll let you be the judge:
2x:
![image](https://user-images.githubusercontent.com/35975961/154869738-ccd74ca5-7a89-4305-842b-096a1ebcae4a.png)
![image](https://user-images.githubusercontent.com/35975961/154869745-12d71045-8172-40f7-a465-79009a8ee126.png)

1x:
![image](https://user-images.githubusercontent.com/35975961/154869789-12c3a93f-4214-4e52-a45a-3110da1cad46.png)
![image](https://user-images.githubusercontent.com/35975961/154869802-5803e8b3-a35f-4cf8-b996-3c5276dd9898.png)

**Comment by maximbaz** [comment]
Mmmmm, did you push some code, could I try locally?

**Comment by ErikReider** [comment]
I'll push the code in a sec. Making sure that the avatar icons are also scaled correctly :)

**Comment by ErikReider** [comment]
#92 should fix this :)

**Comment by maximbaz** [comment]
Now _that_ is what I call **sharp** 🔪  😁 Thank you, wonderful work, it's really good now!
