### ISSUE TITLE
Openning notification panel closes the most recent notification

### ISSUE THREAD

**Issue by maximbaz** [ErikReider/SwayNotificationCenter#91]
First run:

```
notify-send 1
notify-send 2
notify-send 3
```

Wait until all 3 notifications disappear (presumably you are away from your computer).

Then run `swaync-client -op`.

Expected: you see all 3 notifications
Actual: `3` will get removed instantly, and only `1` and `2` will remain.

**Comment by ErikReider** [comment]
Well that's strange. I'll look into it :)

**Comment by ErikReider** [comment]
It seems like it also doesn't hide the popup notifications either

**Comment by ErikReider** [comment]
Ooooh. I know that it is! It gets the enter key press from the terminal execution and activates the first focused notification

**Comment by maximbaz** [comment]
Haha, well that makes sense, also why it wasn't discovered until now 😁 Nice catch!

**Comment by ErikReider** [comment]
Should be fixed now! :)
