### ISSUE TITLE
Notification background color per urgency level

### ISSUE THREAD

**Issue by cyrinux** [ErikReider/SwayNotificationCenter#94]
Hi,

First, thanks for this awesome program !

I can't find how to tweak the notification color per urgency.
What the CSS class name to modify for urgency critical for example?

I try `.notification-content.critical` but this doesn't help.

Regards

**Comment by ErikReider** [comment]
The notifications don't support this feature at the time of writing but would be a great addition :)

**Comment by cyrinux** [comment]
Thanks for your quick reply, I'm not sure I can help you with a PR but I will be happy to try it 😁
