### ISSUE TITLE
White line at bottom of icon until clicked on

### ISSUE THREAD

**Issue by russelltg** [ErikReider/SwayNotificationCenter#99]
My notifications always look something like:
![image](https://user-images.githubusercontent.com/7105082/157357122-a2c84f61-c423-47f7-9e70-aca6888cf6b0.png)

With that small white line at the bottom of the icon. When I click on it, right as my mousebutton goes down, it goes away and looks proper.

Using version 0.4-1 installed via AUR

**Comment by ErikReider** [comment]
What resolution and scaling are you running?
Does this only occur on Spotify notifications?

**Comment by russelltg** [comment]
All notifications, and 4k

**Comment by ErikReider** [comment]
> All notifications, and 4k. 
> 
> Scaling? How would I find that out?

By default the scaling is set to 1x. The scaling makes everything bigger or smaller like the display scaling in Windows. I'm guessing that you're using 1x

**Comment by russelltg** [comment]
Sounds right. I haven't configured it at all yet, so if that's the default then yes.

**Comment by ErikReider** [comment]
Have you tried running it on other resolution? I'm sadly not in possession of a 4K monitor / TV so will be difficult to test :/

**Comment by russelltg** [comment]
Exact same thing happens at 1080p.

Here's a screenrecording--it's interesting how the white line seems to come from the bottom. Here, I click (but do not release) and drag my cursor up and down

https://user-images.githubusercontent.com/7105082/157711512-31ffa4d0-77ca-4fa8-abd3-476df615fd5a.mp4

(and again from 1080p)

https://user-images.githubusercontent.com/7105082/157712052-370fff23-1638-4857-ad31-9fe134df611c.mp4

**Comment by ErikReider** [comment]
Oh that's strange! What GTK theme are you running?

**Comment by russelltg** [comment]
```
$ gsettings get org.gnome.desktop.interface gtk-theme
'Adwaita'
```

**Comment by ErikReider** [comment]
Hmm... Does this occur on any other machines or even if the external 4k monitor is disconnected?

**Comment by ErikReider** [comment]
Are you still experiencing this issue?

**Comment by russelltg** [comment]
Yes, I am, and it still happens when I disconnect the 4k monitor. However, I cannot repro on another machine, so I'm assuming it's a setup issue somehow.

**Comment by ErikReider** [comment]
Any differences between the setups?

**Comment by ErikReider** [comment]
I'll close due to inactivity. You're more than welcome to reopen this issue if you're still experiencing this bug and I'll have another look at it :)
